// This module declaration points to the `mod.rs` file generated by build.rs
// inside the directory specified by `option rust_out` in the .ssot file.
pub mod generated;

// Re-export the generated state machine items for easier use.
// The module name inside `generated` corresponds to the snake_case version
// of the state_machine name defined in the .ssot file.
pub use generated::light_switch::{Event, LightSwitch, State};
// Import the generated Callbacks trait
use generated::light_switch::LightSwitchCallbacks;

// Example function demonstrating how to use the generated state machine.
pub fn run_light_switch_example() {
    println!("\n--- Running Light Switch FSM Example ---");

    // Create a new state machine instance. It starts in the initial state (Off).
    let mut machine = LightSwitch::new();
    println!("Initial state: {:?}", machine.current_state);
    assert_eq!(machine.current_state, State::Off);

    // --- User needs to implement the action functions ---
    // We define dummy implementations here for the example.
    // Define actions for Toggle event
    // REMOVE old impl LightSwitch block
    // impl LightSwitch { ... }

    // --- Simulate events ----

    // Send a Toggle event when Off -> should transition to On
    println!("\nSending Toggle event...");
    let toggle_event_off = Event::Toggle; // No payload struct needed
    match machine.on_event(toggle_event_off) {
        Ok(new_machine) => {
            machine = new_machine; // Update the machine state
            println!("New state: {:?}", machine.current_state);
            assert_eq!(machine.current_state, State::On);
        }
        Err(e) => panic!("Unexpected error from on_event: {}", e), // Handle Err
    }

    // Send a TurnOn event when On -> should result in Ok(self)
    println!("\nSending TurnOn event (while already On)...");
    let turn_on_event =
        Event::TurnOn(generated::light_switch::TurnOnEventPayload { brightness: 100 });
    // Clone machine before calling on_event, as on_event consumes self
    match machine.clone().on_event(turn_on_event.clone()) {
        Ok(new_machine) => {
            // Check if the state *didn't* change compared to the cloned machine state
            assert_eq!(
                new_machine.current_state, machine.current_state,
                "State changed unexpectedly on unhandled event"
            );
            println!("Received Ok(self) for unhandled event as expected.");
            machine = new_machine; // Update machine variable
        }
        Err(e) => panic!("Unexpected error from on_event: {}", e), // Handle Err
    }
    println!("State after TurnOn attempt: {:?}", machine.current_state);
    assert_eq!(machine.current_state, State::On); // State should not change

    // Send a Toggle event when On -> should transition to Off
    println!("\nSending Toggle event...");
    let toggle_event_on = Event::Toggle; // No payload struct needed
    match machine.on_event(toggle_event_on) {
        Ok(new_machine) => {
            machine = new_machine;
            println!("New state: {:?}", machine.current_state);
            assert_eq!(machine.current_state, State::Off);
        }
        Err(e) => panic!("Unexpected error from on_event: {}", e), // Handle Err
    }

    // Send TurnOn event with payload when Off -> should transition to On
    println!("\nSending TurnOn event with payload (while Off)...");
    // Use the correct payload struct name
    let turn_on_payload_event =
        Event::TurnOn(generated::light_switch::TurnOnEventPayload { brightness: 75 });
    match machine.on_event(turn_on_payload_event) {
        Ok(new_machine) => {
            machine = new_machine;
            println!("New state: {:?}", machine.current_state);
            assert_eq!(machine.current_state, State::On);
        }
        Err(e) => panic!("Unexpected error from on_event: {}", e), // Handle Err
    }

    println!("\n--- Example Finished ---");
}

// Implement the trait for the LightSwitch struct
impl LightSwitchCallbacks for LightSwitch {
    // Provide dummy impls satisfying the trait for testing basic transitions
    // Corrected Signatures:
    fn activate_light(&mut self, _event: &Event) {
        println!("Action: activate_light called");
    }
    fn deactivate_light(&mut self, _event: &Event) {
        println!("Action: deactivate_light called");
    }
    fn activate_light_specific(
        &mut self,
        event_data: &generated::light_switch::TurnOnEventPayload,
    ) {
        // Can optionally assert payload in dummy impl for testing
        println!(
            "Action: activate_light_specific brightness={}",
            event_data.brightness
        );
    }
    fn deactivate_light_specific(&mut self, _event: &Event) {
        println!("Action: deactivate_light_specific called");
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    // Use concrete event types imported at top level
    // use generated::light_switch::{Toggle, TurnOn, TurnOff};

    // Dummy implementations required for tests to compile
    // Place them outside individual test functions for broader scope
    // REMOVE old impl LightSwitch block for tests
    // impl LightSwitch { ... }

    // Implement the trait for the test context
    // Remove #[cfg(test)] so it applies to lib code too
    // MOVED outside of cfg(test) block
    // impl LightSwitchCallbacks for LightSwitch { ... }

    #[test]
    fn test_initial_state() {
        let machine = LightSwitch::new();
        assert_eq!(machine.current_state, State::Off);
    }

    #[test]
    fn test_toggle_transitions() {
        let mut machine = LightSwitch::new();
        assert_eq!(machine.current_state, State::Off);

        let event1 = Event::Toggle;
        machine = machine
            .on_event(event1)
            .expect("Transition Off -> On failed");
        assert_eq!(machine.current_state, State::On);

        let event2 = Event::Toggle;
        machine = machine
            .on_event(event2)
            .expect("Transition On -> Off failed");
        assert_eq!(machine.current_state, State::Off);
    }

    #[test]
    fn test_turn_on_off_transitions_with_payload() {
        // Renamed
        let mut machine = LightSwitch::new();
        assert_eq!(machine.current_state, State::Off);

        // Instantiate event with payload using correct struct name
        let event_on =
            Event::TurnOn(generated::light_switch::TurnOnEventPayload { brightness: 50 });
        // Note: This expects activate_light_specific to be implemented
        machine = machine
            .on_event(event_on)
            .expect("Transition Off -> On failed");
        assert_eq!(machine.current_state, State::On);

        let event_off = Event::TurnOff; // No payload
                                        // Note: This expects deactivate_light_specific to be implemented
        machine = machine
            .on_event(event_off)
            .expect("Transition On -> Off failed");
        assert_eq!(machine.current_state, State::Off);
    }

    #[test]
    fn test_unhandled_event_does_not_change_state() {
        // Test renamed for clarity
        let machine = LightSwitch::new(); // Starts Off
        let event_off = Event::TurnOff; // No payload
        let result = machine.clone().on_event(event_off); // Clone machine before calling on_event
        assert!(result.is_ok());
        if let Ok(new_machine) = result {
            println!("Got Ok for unhandled event: TurnOff in Off");
            assert_eq!(
                new_machine.current_state, machine.current_state,
                "State changed on unhandled TurnOff"
            );
        } else {
            panic!("Expected Ok(self) for unhandled event, got Err");
        }

        // Need to instantiate the struct to set state
        // Create a machine and transition it to On state first
        let machine_off = LightSwitch::new();
        let machine_on = machine_off
            .on_event(Event::TurnOn(generated::light_switch::TurnOnEventPayload {
                brightness: 1,
            }))
            .expect("Setup failed");
        assert_eq!(machine_on.current_state, State::On);

        // Use correct payload struct name
        let event_on =
            Event::TurnOn(generated::light_switch::TurnOnEventPayload { brightness: 255 });
        let result_on = machine_on.clone().on_event(event_on); // Clone machine before calling on_event
        assert!(result_on.is_ok());
        if let Ok(new_machine) = result_on {
            println!("Got Ok for unhandled event: TurnOn in On");
            assert_eq!(
                new_machine.current_state, machine_on.current_state,
                "State changed on unhandled TurnOn"
            );
        } else {
            panic!("Expected Ok(self) for unhandled event, got Err");
        }
    }
}
