//! Provides the parser for the `.ssot` (Single Source of Truth) file format.
//!
//! This module uses the `pest` parser generator library to parse `.ssot` files
//! based on the grammar defined in `ssot.pest`. It converts the parsed input
//! into an Abstract Syntax Tree (AST) defined in the `crate::ast` module.
//!
//! The main entry points are the `parse_file` function for parsing a file from disk
//! and the `parse_str` function for parsing a string slice.

use crate::ast::{
    self, Annotation, AnnotationValue, FieldDef, FieldType, MessageItem, SsotFile, StateItem,
    StateMachine, TransitionItem, ImportDeclaration, UseDeclaration, QualifiedIdent, TransitionElement,
};
use pest::iterators::{Pair, Pairs};
use pest::Parser;
use pest_derive::Parser;
use proc_macro2::Ident;
use std::fs;
use std::path::Path;
use thiserror::Error;

/// The Pest parser instance derived from the `ssot.pest` grammar file.
/// This struct itself is typically not used directly, but its generated `parse` method is.
#[derive(Parser)]
#[grammar = "ssot.pest"]
pub struct SsotParser;

/// Enumerates the possible errors that can occur during parsing of an `.ssot` file.
#[derive(Error, Debug)]
pub enum ParseError {
    /// Error encountered while trying to read the input file.
    #[error("Failed to read file: {0}")]
    FileReadError(#[from] std::io::Error),
    /// An error reported directly by the Pest parser, indicating a grammar mismatch.
    #[error("Pest parsing error: {0}")]
    PestError(#[from] Box<pest::error::Error<Rule>>),
    /// An identifier string encountered in the input is not valid according to Rust identifier rules.
    #[error("Invalid identifier: '{0}'")]
    InvalidIdentifier(String),
    /// A numeric literal encountered could not be parsed into the expected integer type (e.g., u64 for ordinals/IDs).
    #[error("Invalid number format: '{0}' - {1}")]
    InvalidNumber(String, String), // value, error message
    /// The file ID (`@0x...;`) format is incorrect or could not be parsed as a hex u64.
    #[error("Invalid file ID format: '{0}'")]
    InvalidFileId(String),
    /// A type name used for a field (e.g., `fieldName: TypeName`) is not recognized as a valid `FieldType`.
    #[error("Invalid type string: '{0}'")]
    InvalidTypeString(String),
    /// A required element according to the grammar or semantics was not found (e.g., missing `$initial` state, missing `file_id`).
    #[error("Missing required element: {0}")]
    MissingElement(String),
    /// A definition with the same name/ordinal was encountered multiple times where uniqueness is required (e.g., duplicate state names).
    #[error("Duplicate definition: {0}")]
    DuplicateDefinition(String),
    /// An internal parser error occurred, indicating a mismatch between the parsing logic and the expected grammar rules.
    /// This usually suggests a bug in the parser implementation itself.
    #[error("Internal parser error: Unexpected rule '{rule:?}' encountered in '{context}'")]
    UnexpectedRule { rule: Rule, context: String },
    /// A general semantic error was detected (e.g., inconsistent use of annotations, violation of specific DSL rules not caught by grammar).
    #[error("Semantic error: {0}")]
    SemanticError(String),
}

/// Parses the content of a `.ssot` file located at the given path.
///
/// Reads the file content and then uses `parse_str` to perform the actual parsing.
///
/// # Arguments
///
/// * `path` - A type that can be converted into a `Path` reference (e.g., `&str`, `PathBuf`).
///
/// # Errors
///
/// Returns a `ParseError` if:
/// * The file cannot be read (`ParseError::FileReadError`).
/// * The content does not conform to the `.ssot` grammar (`ParseError::PestError`).
/// * The content has syntactic or semantic errors (e.g., `ParseError::InvalidIdentifier`, `ParseError::MissingElement`).
///
/// # Example
///
/// ```no_run
/// use fsm_dsl::parser::parse_file;
///
/// match parse_file("example.ssot") {
///     Ok(ast) => println!("Successfully parsed: {:?}", ast),
///     Err(e) => eprintln!("Parsing failed: {}", e),
/// }
/// ```
pub fn parse_file<P: AsRef<Path>>(path: P) -> Result<SsotFile, ParseError> {
    let content = fs::read_to_string(path)?;
    parse_str(&content)
}

/// Parses a string slice containing the content of a `.ssot` file.
///
/// This is the core parsing function that utilizes the `SsotParser` generated by `pest`.
///
/// # Arguments
///
/// * `input` - A string slice (`&str`) containing the `.ssot` definition.
///
/// # Errors
///
/// Returns a `ParseError` if:
/// * The input string does not conform to the `.ssot` grammar (`ParseError::PestError`).
/// * The input has syntactic or semantic errors (e.g., `ParseError::InvalidIdentifier`, `ParseError::MissingElement`).
///
/// # Example
///
/// ```
/// use fsm_dsl::parser::parse_str;
///
/// let ssot_content = r#"
/// @0x123456789abcdef0;
///
/// state_machine MyMachine {
///     $initial(Idle);
///     states {
///         Idle @0;
///         Running @1;
///     }
///     events {
///         Start @0 { data: Text @0; }
///     }
///     transitions {
///         from Idle to Running {
///             on Start @0;
///         }
///     }
/// }
/// "#;
///
/// match parse_str(ssot_content) {
///     Ok(ast) => println!("Parsed AST"), // Actual AST check omitted for brevity
///     Err(e) => eprintln!("Parsing failed: {}", e),
/// }
/// ```
pub fn parse_str(input: &str) -> Result<SsotFile, ParseError> {
    let mut pairs = SsotParser::parse(Rule::ssot_file, input)
        .map_err(|e| ParseError::PestError(Box::new(e)))?;

    // Get the single top-level ssot_file pair
    let ssot_file_pair = pairs.next().ok_or_else(|| {
        ParseError::SemanticError("Parser did not return a top-level ssot_file rule".to_string())
    })?;
    if ssot_file_pair.as_rule() != Rule::ssot_file {
        return Err(ParseError::SemanticError(format!(
            "Expected ssot_file rule, got {:?}",
            ssot_file_pair.as_rule()
        )));
    }

    let mut file_id: Option<u64> = None;
    let mut package_declaration: Option<String> = None;
    let mut imports: Vec<ImportDeclaration> = Vec::new();
    let mut items: Vec<ast::TopLevelItem> = Vec::new();

    // Iterate over the *inner* pairs of the ssot_file rule
    for pair in ssot_file_pair.into_inner() {
        match pair.as_rule() {
            Rule::file_id => {
                file_id = Some(parse_hex_literal(pair.into_inner().next().unwrap())?);
            }
            Rule::package_decl => {
                package_declaration = Some(parse_package_name(pair.into_inner().next().unwrap())?);
            }
            Rule::import_decl => {
                let package_name = parse_package_name(pair.into_inner().next().unwrap())?;
                imports.push(ImportDeclaration { package_name });
            }
            Rule::top_level_item => {
                let inner_item = pair.into_inner().next().ok_or_else(|| {
                    ParseError::SemanticError("Empty top_level_item encountered".to_string())
                })?;
                match inner_item.as_rule() {
                    Rule::annotation => {
                        items.push(ast::TopLevelItem::Annotation(parse_annotation(inner_item)?));
                    }
                    Rule::state_machine => {
                        items.push(ast::TopLevelItem::StateMachine(parse_state_machine(inner_item)?));
                    }
                    Rule::struct_def => {
                        items.push(ast::TopLevelItem::StructDefinition(parse_struct_def(inner_item)?));
                    }
                    _ => {
                        // Should not happen if grammar is correct
                        return Err(ParseError::UnexpectedRule {
                            rule: inner_item.as_rule(),
                            context: "inside top_level_item".to_string(),
                        });
                    }
                }
            }
            Rule::WHITESPACE | Rule::COMMENT => { /* ignore */ }
            Rule::EOI => break, // EOI marks the end of the inner pairs for ssot_file
            _ => {
                return Err(ParseError::UnexpectedRule {
                    rule: pair.as_rule(),
                    context: "ssot_file inner elements".to_string(),
                });
            }
        }
    }

    // Check for required file_id after parsing all inner elements
    if file_id.is_none() {
        return Err(ParseError::MissingElement(
            "file ID (@0x...;) required at top level".to_string(),
        ));
    }

    Ok(SsotFile {
        file_id: file_id.unwrap(), // Safe now after check
        package_declaration,
        imports,
        items,
    })
}

/// Parses an annotation rule (e.g., `$name(value);` or `$name;`).
///
/// Corresponds to the `annotation` rule in `ssot.pest`.
fn parse_annotation(pair: Pair<Rule>) -> Result<Annotation, ParseError> {
    let mut inner = pair.into_inner();
    let name = parse_ident(inner.next().unwrap())?;

    // Check if the optional annotation_value is present
    let value = if let Some(value_pair) = inner.peek() {
        // If the next pair is annotation_value, parse it
        if value_pair.as_rule() == Rule::annotation_value {
            // Consume the pair and parse it
            let parsed_value = parse_annotation_value(inner.next().unwrap())?;
            Some(parsed_value)
        } else {
            // Next pair is not annotation_value (likely the semicolon), so no value
            None
        }
    } else {
        // No more pairs after identifier, so no value
        None
    };

    // We don't need to consume the semicolon explicitly as it's part of the grammar rule
    // and handled by Pest moving to the next item.

    Ok(Annotation { name, value })
}

/// Parses the value part of an annotation (inside the parentheses).
///
/// Corresponds to the `annotation_value` and `annotation_value_inner` rules.
fn parse_annotation_value(pair: Pair<Rule>) -> Result<AnnotationValue, ParseError> {
    // pair matches annotation_value rule: "(" ~ annotation_value_inner? ~ ")"
    if let Some(annotation_value_inner_pair) = pair.into_inner().next() {
        if annotation_value_inner_pair.as_rule() == Rule::annotation_value_inner {
            if let Some(actual_content_pair) = annotation_value_inner_pair.into_inner().next() {
                match actual_content_pair.as_rule() {
                    Rule::identifier => Ok(AnnotationValue::Identifier(parse_ident(
                        actual_content_pair,
                    )?)),
                    Rule::array_literal => {
                        let strings = actual_content_pair
                            .into_inner()
                            .map(|p| unescape_string(p.as_str()))
                            .collect();
                        Ok(AnnotationValue::ArrayLiteral(strings))
                    }
                    // Handle the literal_value wrapper rule
                    Rule::literal_value => {
                        // Get the specific literal *inside* literal_value
                        if let Some(specific_literal_pair) = actual_content_pair.into_inner().next()
                        {
                            match specific_literal_pair.as_rule() {
                                Rule::string_literal => Ok(AnnotationValue::StringLiteral(
                                    unescape_string(specific_literal_pair.as_str()),
                                )),
                                Rule::boolean_literal => Ok(AnnotationValue::BooleanLiteral(
                                    specific_literal_pair.as_str() == "true",
                                )),
                                Rule::number_literal => {
                                    let num_str = specific_literal_pair.as_str();
                                    let num = num_str.parse::<i64>().map_err(|e| {
                                        ParseError::InvalidNumber(
                                            num_str.to_string(),
                                            e.to_string(),
                                        )
                                    })?;
                                    Ok(AnnotationValue::NumberLiteral(num))
                                }
                                _ => Err(ParseError::UnexpectedRule {
                                    rule: specific_literal_pair.as_rule(),
                                    context: "specific literal value".to_string(),
                                }),
                            }
                        } else {
                            Err(ParseError::MissingElement(
                                "specific literal content inside literal_value".to_string(),
                            ))
                        }
                    }
                    _ => Err(ParseError::UnexpectedRule {
                        rule: actual_content_pair.as_rule(),
                        context:
                            "annotation value content (expected identifier, array, or literal)"
                                .to_string(),
                    }),
                }
            } else {
                Err(ParseError::MissingElement(
                    "actual annotation value content".to_string(),
                ))
            }
        } else {
            Err(ParseError::UnexpectedRule {
                rule: annotation_value_inner_pair.as_rule(),
                context: "expected annotation_value_inner".to_string(),
            })
        }
    } else {
        Err(ParseError::MissingElement(
            "annotation value content".to_string(),
        ))
    }
}

/// Parses a state machine definition block.
///
/// Corresponds to the `state_machine` rule.
fn parse_state_machine(pair: Pair<Rule>) -> Result<StateMachine, ParseError> {
    let mut inner = pair.into_inner();
    let name = parse_ident(inner.next().unwrap())?;
    println!("Parsing state_machine body for: {}", name);

    let mut annotations = Vec::new();
    let mut use_declarations = Vec::new();
    let mut states = Vec::new();
    let mut events = Vec::new();
    let mut transitions = Vec::new();
    let mut context = Vec::new();

    // Iterate over items inside the stateMachine block {}
    for item_pair in inner {
        // Handle the state_machine_item wrapper rule
        let actual_item_pair = if item_pair.as_rule() == Rule::state_machine_item {
            item_pair.into_inner().next().ok_or_else(|| {
                ParseError::SemanticError("Empty state_machine_item encountered".to_string())
            })?
        } else {
            // If it's not state_machine_item, it might be EOI or an error
            // Let the match handle other cases like WHITESPACE, COMMENT, etc.
            item_pair
        };

        let rule = actual_item_pair.as_rule();
        println!("  -> Processing rule: {:?}", rule);
        match rule {
            Rule::annotation => {
                println!("    -> Matched Rule::annotation");
                let annotation = parse_annotation(actual_item_pair)?;
                if annotation.name == "initial" {
                    // annotation.value is Option<AnnotationValue>
                    // Borrow ident with `ref` to avoid moving it out of annotation.value
                    if let Some(AnnotationValue::Identifier(_)) = annotation.value {
                        // Validation: Check if value is an identifier.
                        // We don't store it separately anymore, it stays in annotations.
                        // initial_state = Some(ident.clone()); // Clone if we need to store it
                    } else {
                        // Handle cases where $initial is present but value is not an identifier or is None
                        return Err(ParseError::SemanticError(format!(
                            "$initial annotation requires a state identifier argument, got: {:?}",
                            annotation.value
                        )));
                    }
                }
                annotations.push(annotation);
            }
            Rule::use_decl => {
                let target = parse_qualified_ident(actual_item_pair.into_inner().next().unwrap())?;
                use_declarations.push(UseDeclaration { target });
            }
            Rule::state_enum => {
                println!("    -> Matched Rule::state_enum");
                states = parse_state_enum(actual_item_pair)?;
            }
            Rule::event_definitions => {
                println!("    -> Matched Rule::event_definitions");
                let (parsed_events, block_uses) = parse_event_definitions(actual_item_pair)?;
                events = parsed_events;
                use_declarations.extend(block_uses);
            }
            Rule::transitions_block => {
                println!("    -> Matched Rule::transitions_block");
                transitions = parse_transitions_block(actual_item_pair)?;
            }
            // Rule::context_block => context_fields = parse_context_block(actual_item_pair)?,
            Rule::WHITESPACE | Rule::COMMENT => { /* ignore */ }
            // EOI might appear if the block is empty or at the end
            Rule::EOI => break,
            _ => {
                println!("    -> FAILED: Unexpected rule {:?}", rule);
                // Provide more context in the error
                return Err(ParseError::UnexpectedRule {
                    rule,
                    context: format!(
                        "inside stateMachine '{}' block {{}}; expected annotation, states, events, or transitions",
                        name
                    ),
                });
            }
        }
    }

    if states.is_empty() {
        return Err(ParseError::MissingElement(
            "At least one state variant must be defined".to_string(),
        ));
    }

    println!("Finished parsing state_machine: {}", name);
    Ok(StateMachine {
        name,
        annotations,
        use_declarations,
        states,
        events,
        transitions,
        context,
    })
}

/// Parses the `states` block within a state machine.
///
/// Corresponds to the `state_enum` rule (historical name).
fn parse_state_enum(pair: Pair<Rule>) -> Result<Vec<StateItem>, ParseError> {
    pair.into_inner()
        // Revert filter to original state_variant rule
        .filter(|p| p.as_rule() == Rule::state_variant)
        .map(parse_state_item)
        .collect()
}

/// Parses a single state definition within the `states` block.
///
/// Can handle both simple states (`State @N;`) and states with bodies containing
/// entry/exit actions (`State @N { entry: ...; exit: ...; }`).
/// Corresponds to the `state_item` rule.
fn parse_state_item(pair: Pair<Rule>) -> Result<ast::StateItem, ParseError> {
    let inner = pair.into_inner(); // Consumes the outer state_variant rule
    let mut annotations = Vec::new();
    let mut name: Option<Ident> = None;
    let mut ordinal: Option<u64> = None;
    let mut entry_actions: Vec<Ident> = Vec::new();
    let mut exit_actions: Vec<Ident> = Vec::new();

    // Process elements *inside* state_variant
    for item_pair in inner {
        match item_pair.as_rule() {
            Rule::optional_annotations => {
                // Parse annotations within optional_annotations
                for annotation_pair in item_pair.into_inner() {
                    if annotation_pair.as_rule() == Rule::annotation {
                        annotations.push(parse_annotation(annotation_pair)?);
                    }
                }
            }
            Rule::identifier => name = Some(parse_ident(item_pair)?),
            Rule::ordinal => ordinal = Some(parse_ordinal(item_pair)?),
            // Handle the optional state_body_content
            Rule::state_body_content => {
                // item_pair is state_body_content ({ ... })
                for body_item_rule in item_pair.into_inner() {
                    // Renamed for clarity
                    match body_item_rule.as_rule() {
                        Rule::state_body_item => {
                            // Expect state_body_item here
                            // Now look inside state_body_item for entry_action or exit_action
                            let inner_action_pair =
                                body_item_rule.into_inner().next().ok_or_else(|| {
                                    ParseError::UnexpectedRule {
                                        rule: Rule::state_body_item,
                                        context: "empty state_body_item?".to_string(),
                                    }
                                })?;
                            match inner_action_pair.as_rule() {
                                Rule::entry_action => {
                                    let action_ident_pair = inner_action_pair
                                        .into_inner()
                                        .find(|p| p.as_rule() == Rule::identifier)
                                        .ok_or_else(|| {
                                            ParseError::MissingElement(
                                                "entry action identifier".to_string(),
                                            )
                                        })?;
                                    entry_actions.push(parse_ident(action_ident_pair)?);
                                }
                                Rule::exit_action => {
                                    let action_ident_pair = inner_action_pair
                                        .into_inner()
                                        .find(|p| p.as_rule() == Rule::identifier)
                                        .ok_or_else(|| {
                                            ParseError::MissingElement(
                                                "exit action identifier".to_string(),
                                            )
                                        })?;
                                    exit_actions.push(parse_ident(action_ident_pair)?);
                                }
                                _ => {
                                    // Unexpected rule inside state_body_item
                                    return Err(ParseError::UnexpectedRule {
                                        rule: inner_action_pair.as_rule(),
                                        context: "inside state_body_item (expected entry_action or exit_action)".to_string(),
                                    });
                                }
                            }
                        }
                        // Ignore whitespace/comments between state_body_items
                        Rule::WHITESPACE | Rule::COMMENT | Rule::optional_whitespace => { /* Ignore */
                        }
                        // Any other rule directly inside state_body_content is unexpected
                        _ => {
                            return Err(ParseError::UnexpectedRule {
                                rule: body_item_rule.as_rule(),
                                context:
                                    "inside state_body_content block {} (expected state_body_item)"
                                        .to_string(),
                            });
                        }
                    }
                }
            }
            // Ignore whitespace/comments between elements
            Rule::WHITESPACE | Rule::COMMENT | Rule::optional_whitespace => { /* ignore */ }
            // The semicolon is implicitly handled by the grammar moving past it
            _ => {
                return Err(ParseError::UnexpectedRule {
                    rule: item_pair.as_rule(),
                    context: "state_variant inner definition".to_string(),
                });
            }
        }
    }

    Ok(ast::StateItem {
        annotations,
        name: name.ok_or_else(|| ParseError::MissingElement("state name".to_string()))?,
        ordinal: ordinal
            .ok_or_else(|| ParseError::MissingElement("state ordinal (@N)".to_string()))?,
        entry_actions,
        exit_actions,
    })
}

/// Parses the `events` block within a state machine.
/// Corresponds to the `event_definitions` rule.
fn parse_event_definitions(pair: Pair<Rule>) -> Result<(Vec<MessageItem>, Vec<UseDeclaration>), ParseError> {
    let mut events = Vec::new();
    let mut use_declarations = Vec::new();
    for item_pair in pair.into_inner() {
        match item_pair.as_rule() {
            Rule::event_struct => events.push(parse_event_struct(item_pair)?),
            Rule::use_decl => {
                let target = parse_qualified_ident(item_pair.into_inner().next().unwrap())?;
                use_declarations.push(UseDeclaration { target });
            }
            Rule::WHITESPACE | Rule::COMMENT => {} // Ignore
            _ => {
                return Err(ParseError::UnexpectedRule {
                    rule: item_pair.as_rule(),
                    context: "events_block inner elements (event_item)".to_string(),
                });
            }
        }
    }
    Ok((events, use_declarations))
}

/// Parses a single event definition within the `events` block.
///
/// Handles events with or without payload fields.
/// Corresponds to the `event_struct` rule.
fn parse_event_struct(pair: Pair<Rule>) -> Result<MessageItem, ParseError> {
    // pair should match Rule::event_struct
    debug_assert_eq!(pair.as_rule(), Rule::event_struct);

    let mut inner = pair.into_inner();
    let mut annotations = Vec::new();

    // 1. Parse optional annotations first
    if let Some(potential_annotations_pair) = inner.peek() {
        if potential_annotations_pair.as_rule() == Rule::optional_annotations {
            annotations = potential_annotations_pair
                .into_inner() // Iterate inside optional_annotations
                .map(parse_annotation)
                .collect::<Result<_, _>>()?;
            inner.next(); // Consume the optional_annotations pair
        }
        // If not Rule::optional_annotations, it should be Rule::identifier (handled next)
    }

    // 2. Consume the "event" keyword (implicitly handled by grammar structure, not a rule itself)
    // No, the rule is `optional_annotations ~ "event" ~ identifier ...`
    // We don't get a pair for the literal "event".

    // 3. Parse identifier (event name)
    let name_pair = inner.next().ok_or_else(|| {
        ParseError::MissingElement("event name after 'event' keyword".to_string())
    })?;
    if name_pair.as_rule() != Rule::identifier {
        return Err(ParseError::UnexpectedRule {
            rule: name_pair.as_rule(),
            context: "expected event name (identifier)".to_string(),
        });
    }
    let name = parse_ident(name_pair)?;

    // 4. Parse ordinal
    let ordinal_pair = inner
        .next()
        .ok_or_else(|| ParseError::MissingElement("event ordinal after name".to_string()))?;
    if ordinal_pair.as_rule() != Rule::ordinal {
        return Err(ParseError::UnexpectedRule {
            rule: ordinal_pair.as_rule(),
            context: "expected event ordinal".to_string(),
        });
    }
    let ordinal = parse_ordinal(ordinal_pair)?;

    // 5. Parse event body or terminator
    let mut fields: Vec<FieldDef> = Vec::new();
    let body_or_terminator_pair = inner.next().ok_or_else(|| {
        ParseError::MissingElement("event body {} or terminator ; after ordinal".to_string())
    })?;

    match body_or_terminator_pair.as_rule() {
        Rule::event_body => {
            // Iterate inside the event_body pair for event_fields
            for field_pair in body_or_terminator_pair.into_inner() {
                match field_pair.as_rule() {
                    Rule::event_field => {
                        fields.push(parse_event_field(field_pair)?);
                    }
                    Rule::WHITESPACE | Rule::COMMENT => { /* ignore */ }
                    _ => {
                        return Err(ParseError::UnexpectedRule {
                            rule: field_pair.as_rule(),
                            context: "inside event_body".to_string(),
                        })
                    }
                }
            }
        }
        Rule::event_terminator => {
            // No fields to parse for terminator
        }
        _ => {
            return Err(ParseError::UnexpectedRule {
                rule: body_or_terminator_pair.as_rule(),
                context: "expected event_body or event_terminator".to_string(),
            })
        }
    }

    // Ensure no extra pairs are left
    if inner.next().is_some() {
        return Err(ParseError::SemanticError(
            "Unexpected tokens after event definition".to_string(),
        ));
    }

    Ok(MessageItem {
        annotations,
        name,
        ordinal,
        fields,
    })
}

/// Parses a single field definition within an event's payload.
///
/// Corresponds to the `event_field` rule.
fn parse_event_field(pair: Pair<Rule>) -> Result<FieldDef, ParseError> {
    let mut inner = pair.into_inner();
    let mut annotations = Vec::new();

    // Peek and parse optional annotations
    if let Some(first) = inner.peek() {
        if first.as_rule() == Rule::optional_annotations {
            annotations = first
                .into_inner()
                .map(parse_annotation)
                .collect::<Result<_, _>>()?;
            inner.next();
        }
    }

    let name = parse_ident(
        inner
            .next()
            .ok_or(ParseError::MissingElement("field name".to_string()))?,
    )?;
    let ordinal = parse_ordinal(
        inner
            .next()
            .ok_or(ParseError::MissingElement("field ordinal".to_string()))?,
    )?;

    let type_pair = inner
        .next()
        .ok_or(ParseError::MissingElement("field type".to_string()))?;
    let actual_type_pair = if type_pair.as_rule() == Rule::r#type {
        type_pair
            .into_inner()
            .next()
            .ok_or(ParseError::UnexpectedRule {
                rule: Rule::r#type,
                context: "empty inner type".to_string(),
            })?
    } else {
        type_pair
    };
    let field_type = parse_field_type(actual_type_pair)?;

    Ok(FieldDef {
        annotations, // Add parsed annotations
        name,
        ordinal,
        field_type,
    })
}

/// Parses a field type identifier string into a `FieldType` enum variant.
///
/// Handles primitive types (like `UInt32`, `Text`) and potentially list types or identifiers.
/// Corresponds to the `field_type` rule.
fn parse_field_type(pair: Pair<Rule>) -> Result<FieldType, ParseError> {
    // If the received pair is the generic 'type' rule, get its specific inner rule.
    let rule = pair.as_rule(); // Get the rule *before* potentially moving pair
    let specific_pair = if rule == Rule::r#type {
        pair.into_inner().next().ok_or(ParseError::UnexpectedRule {
            rule, // Use the saved rule
            context: "empty type rule?".to_string(),
        })?
    } else {
        pair // Assume it's already the specific rule (primitive, list, ident)
    };

    match specific_pair.as_rule() {
        Rule::primitive_type => match specific_pair.as_str() {
            "Void" => Ok(FieldType::Void),
            "Bool" => Ok(FieldType::Bool),
            "Int8" => Ok(FieldType::Int8),
            "Int16" => Ok(FieldType::Int16),
            "Int32" => Ok(FieldType::Int32),
            "Int64" => Ok(FieldType::Int64),
            "UInt8" => Ok(FieldType::UInt8),
            "UInt16" => Ok(FieldType::UInt16),
            "UInt32" => Ok(FieldType::UInt32),
            "UInt64" => Ok(FieldType::UInt64),
            "Float32" => Ok(FieldType::Float32),
            "Float64" => Ok(FieldType::Float64),
            "Text" => Ok(FieldType::Text),
            "Data" => Ok(FieldType::Data),
            _ => Err(ParseError::InvalidTypeString(
                specific_pair.as_str().to_string(),
            )),
        },
        Rule::list_type => {
            // Get the inner type rule (which should be Rule::type)
            let inner_type_pair_generic = specific_pair.into_inner().next().unwrap();
            // Recursively call parse_field_type, which will now handle unwrapping Rule::type
            let inner_type = parse_field_type(inner_type_pair_generic)?;
            Ok(FieldType::List(Box::new(inner_type)))
        }
        Rule::identifier => Ok(FieldType::Identifier(parse_ident(specific_pair)?)),
        _ => Err(ParseError::UnexpectedRule {
            rule: specific_pair.as_rule(),
            context: "field type".to_string(),
        }),
    }
}

/// Parses a single transition definition within the `transitions` block.
///
/// Corresponds to the `transition_definition` rule.
fn parse_transition_definition(pair: Pair<Rule>) -> Result<TransitionItem, ParseError> {
    println!("Parsing transition_definition...");
    let mut inner = pair.into_inner();

    // Directly peek and consume the optional transition name
    let name = if inner
        .peek()
        .is_some_and(|p| p.as_rule() == Rule::identifier)
    {
        let name_pair = inner.next().unwrap(); // Consume if peeked
        let parsed_name = parse_ident(name_pair)?;
        println!("Parsed optional transition name: {}", parsed_name);
        Some(parsed_name)
    } else {
        println!("No optional transition name found.");
        None
    };

    // Consume required 'from' state identifier
    let from_state_pair = inner
        .next()
        .ok_or_else(|| ParseError::MissingElement("from state identifier".to_string()))?;
    if from_state_pair.as_rule() != Rule::identifier {
        return Err(ParseError::UnexpectedRule {
            rule: from_state_pair.as_rule(),
            context: "Expected 'from' state identifier".to_string(),
        });
    }
    let from_state_ident = parse_ident(from_state_pair)?;
    println!("Parsed from_state: {}", from_state_ident);

    // Consume required 'to' state identifier
    let to_state_pair = inner
        .next()
        .ok_or_else(|| ParseError::MissingElement("to state identifier".to_string()))?;
    if to_state_pair.as_rule() != Rule::identifier {
        return Err(ParseError::UnexpectedRule {
            rule: to_state_pair.as_rule(),
            context: "Expected 'to' state identifier".to_string(),
        });
    }
    let to_state_ident = parse_ident(to_state_pair)?;
    println!("Parsed to_state: {}", to_state_ident);

    let mut annotations = Vec::new();
    let mut elements = Vec::new();

    // Process remaining elements (transition_elements or annotations within the {})
    for current_pair in inner {
        // This should now only contain items within the curly braces
        match current_pair.as_rule() {
            Rule::annotation => {
                let annotation = parse_annotation(current_pair)?;
                println!("Parsed annotation in transition: {:?}", annotation);
                annotations.push(annotation);
            }
            Rule::transition_element => {
                let element = parse_transition_element(current_pair)?;
                println!("Parsed transition element: {:?}", element);
                elements.push(element);
            }
            // Add explicit ignores for WHITESPACE/COMMENT if they leak through somehow
            Rule::WHITESPACE | Rule::COMMENT => { /* Ignore */ }
            _ => {
                println!(
                    "Unexpected rule inside transition body: {:?}",
                    current_pair.as_rule()
                );
                return Err(ParseError::UnexpectedRule {
                    rule: current_pair.as_rule(),
                    context: "transition_definition body".to_string(),
                });
            }
        }
    }

    if !elements
        .iter()
        .any(|e| matches!(e, ast::TransitionElement::On { .. }))
    {
        return Err(ParseError::MissingElement(
            "Transition must have at least one 'on' clause".to_string(),
        ));
    }

    println!("Finished parsing transition_definition.");
    Ok(TransitionItem {
        name,
        from: from_state_ident,
        to: to_state_ident,
        annotations,
        elements,
    })
}

/// Parses a single element within a transition definition (`on`, `guard`, or `action`).
///
/// Corresponds to the `transition_element` rule.
fn parse_transition_element(pair: Pair<Rule>) -> Result<ast::TransitionElement, ParseError> {
    let inner_pair = pair.into_inner().next().unwrap();
    let rule = inner_pair.as_rule();

    let mut clause_inner = inner_pair.into_inner();
    let ordinal = parse_ordinal(clause_inner.next().unwrap())?;
    let ident = parse_ident(clause_inner.next().unwrap())?;

    match rule {
        Rule::on_clause => Ok(ast::TransitionElement::On {
            ordinal,
            event: ident,
        }),
        Rule::guard_clause => Ok(ast::TransitionElement::Guard {
            ordinal,
            function: ident,
        }),
        Rule::action_clause => Ok(ast::TransitionElement::Action {
            ordinal,
            function: ident,
        }),
        _ => Err(ParseError::UnexpectedRule {
            rule,
            context: "transition element".to_string(),
        }),
    }
}

/// Parses a generic identifier string into a `proc_macro2::Ident`.
///
/// Corresponds to the `identifier` rule.
fn parse_ident(pair: Pair<Rule>) -> Result<Ident, ParseError> {
    let ident_str = pair.as_str();
    syn::parse_str::<Ident>(ident_str)
        .map_err(|_| ParseError::InvalidIdentifier(ident_str.to_string()))
}

/// Parses an ordinal (`@N`) into a `u64`.
///
/// Corresponds to the `ordinal` rule.
fn parse_ordinal(pair: Pair<Rule>) -> Result<u64, ParseError> {
    let num_str = pair.as_str();
    num_str
        .parse::<u64>()
        .map_err(|e| ParseError::InvalidNumber(num_str.to_string(), e.to_string()))
}

/// Parses a hexadecimal literal (`0x...`) into a `u64`.
///
/// Used primarily for the file ID.
/// Corresponds to the `hex_literal` rule.
fn parse_hex_literal(pair: Pair<Rule>) -> Result<u64, ParseError> {
    let hex_str = pair.as_str().trim_start_matches("0x");
    u64::from_str_radix(hex_str, 16)
        .map_err(|e| ParseError::InvalidNumber(hex_str.to_string(), e.to_string()))
}

/// Parses a package name rule (dot-separated identifiers) into a String.
fn parse_package_name(pair: Pair<Rule>) -> Result<String, ParseError> {
    // package_name rule is atomic (@) so just get the string value
    Ok(pair.as_str().to_string())
}

/// Parses a qualified identifier rule (ident or ns.ident) into an ast::QualifiedIdent.
fn parse_qualified_ident(pair: Pair<Rule>) -> Result<QualifiedIdent, ParseError> {
    let mut inner = pair.into_inner();
    let first_ident_pair = inner.next().ok_or_else(|| ParseError::SemanticError(
        "Expected identifier within qualified_ident rule".to_string(),
    ))?;
    let first_ident = parse_ident(first_ident_pair)?;

    if let Some(second_ident_pair) = inner.next() {
        // If there's a second part, it's qualifier.name
        let second_ident = parse_ident(second_ident_pair)?;
        Ok(QualifiedIdent::Qualified {
            qualifier: first_ident,
            name: second_ident,
        })
    } else {
        // Only one part, it's a simple identifier
        Ok(QualifiedIdent::Simple(first_ident))
    }
}

/// Unescapes string literals found in the grammar (removes surrounding quotes and handles escapes).
///
/// Note: This is a basic implementation and might need refinement depending on supported escape sequences.
fn unescape_string(s: &str) -> String {
    // Remove the outer quotes
    let s = &s[1..s.len() - 1];
    let mut result = String::with_capacity(s.len());
    let mut chars = s.chars().peekable();

    while let Some(c) = chars.next() {
        if c == '\\' {
            if let Some(next_c) = chars.peek() {
                match next_c {
                    '\n' => {
                        chars.next();
                        continue;
                    }
                    '"' | '\\' | '/' => {
                        result.push(*next_c);
                        chars.next();
                    }
                    'b' => {
                        result.push('\x08');
                        chars.next();
                    }
                    'f' => {
                        result.push('\x0C');
                        chars.next();
                    }
                    'n' => {
                        result.push('\n');
                        chars.next();
                    }
                    'r' => {
                        result.push('\r');
                        chars.next();
                    }
                    't' => {
                        result.push('\t');
                        chars.next();
                    }
                    'u' => {
                        chars.next();
                        let mut hex_code = String::with_capacity(4);
                        for _ in 0..4 {
                            if let Some(hex_char) = chars.next() {
                                if hex_char.is_ascii_hexdigit() {
                                    hex_code.push(hex_char);
                                } else {
                                    result.push('\\');
                                    result.push('u');
                                    result.push_str(&hex_code);
                                    result.push(hex_char);
                                    break;
                                }
                            } else {
                                result.push('\\');
                                result.push('u');
                                result.push_str(&hex_code);
                                break;
                            }
                        }
                        if hex_code.len() == 4 {
                            if let Ok(code_point) = u32::from_str_radix(&hex_code, 16) {
                                if let Some(unicode_char) = std::char::from_u32(code_point) {
                                    result.push(unicode_char);
                                } else {
                                    result.push('\\');
                                    result.push('u');
                                    result.push_str(&hex_code);
                                }
                            } else {
                                result.push('\\');
                                result.push('u');
                                result.push_str(&hex_code);
                            }
                        }
                    }
                    _ => {
                        result.push('\\');
                    }
                }
            } else {
                result.push('\\');
            }
        } else {
            result.push(c);
        }
    }

    result
}

/// Parses the `transitions` block within a state machine.
///
/// Corresponds to the `transitions_block` rule.
fn parse_transitions_block(pair: Pair<Rule>) -> Result<Vec<TransitionItem>, ParseError> {
    println!("Parsing transitions_block...");
    let mut parsed_transitions = Vec::new();
    for inner_pair in pair.into_inner() {
        match inner_pair.as_rule() {
            Rule::transition_definition => {
                println!("  -> Parsing transition_definition within block");
                parsed_transitions.push(parse_transition_definition(inner_pair)?);
            }
            _ => {
                println!(
                    "    -> Matched UNEXPECTED rule within transitions_block: {:?}",
                    inner_pair.as_rule()
                );
                return Err(ParseError::UnexpectedRule {
                    rule: inner_pair.as_rule(),
                    context: "transitions block body".to_string(),
                });
            }
        }
    }
    println!("Finished parsing transitions_block.");
    Ok(parsed_transitions)
}

// New function to parse top-level struct definitions
fn parse_struct_def(pair: Pair<Rule>) -> Result<ast::StructDef, ParseError> {
    debug_assert_eq!(pair.as_rule(), Rule::struct_def);
    let mut inner = pair.into_inner();

    let mut annotations = Vec::new();
    let mut name: Option<Ident> = None;
    let mut fields = Vec::new();

    for item in inner {
        match item.as_rule() {
            Rule::annotation => {
                annotations.push(parse_annotation(item)?);
            }
            Rule::ident => {
                name = Some(parse_ident(item)?);
            }
            Rule::struct_body => {
                // Parse fields inside the body
                for field_pair in item.into_inner() {
                    if field_pair.as_rule() == Rule::struct_field {
                         // Unwrap the struct_field to get the actual event_field
                         let event_field_pair = field_pair.into_inner().next().unwrap();
                         if event_field_pair.as_rule() == Rule::event_field {
                             fields.push(parse_event_field(event_field_pair)?);
                         } else {
                             return Err(ParseError::UnexpectedRule {
                                rule: event_field_pair.as_rule(),
                                context: "inside struct_field".to_string(),
                            });
                         }
                    } else if field_pair.as_rule() != Rule::WHITESPACE && field_pair.as_rule() != Rule::COMMENT {
                         return Err(ParseError::UnexpectedRule {
                            rule: field_pair.as_rule(),
                            context: "inside struct_body".to_string(),
                        });
                    }
                }
            }
            // Allow empty body (struct Foo;)
            Rule::WHITESPACE | Rule::COMMENT => { /* ignore */ }
            _ => {
                return Err(ParseError::UnexpectedRule {
                    rule: item.as_rule(),
                    context: "struct_def inner elements".to_string(),
                });
            }
        }
    }

    Ok(ast::StructDef {
        annotations,
        name: name.ok_or_else(|| ParseError::MissingElement("struct name".to_string()))?,
        fields,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    use pretty_assertions::assert_eq;

    // Helper to create Ident for tests
    // fn ident(s: &str) -> Ident {
    //     Ident::new(s, Span::call_site())
    // }

    #[test]
    fn test_parse_valid_input() {
        let input = r#"
            @0x123456789ABCDEF0;
            package my.package;

            $top_level_derive(Debug, Clone);

            stateMachine MyMachine {
                $initial(Idle);
                $description("A simple state machine.");

                context {
                    counter: Int32;
                    description: Text @1;
                    maybeFlag: Bool;
                }

                states {
                    Idle @0;
                    Running @1 {
                        entry / action1, action2;
                        exit / cleanup;
                    }
                }

                events {
                    Start @0 {
                        source: Text;
                    }
                    Stop @1;
                    Internal @2;
                }

                transitions {
                    from Idle to Running {
                        on @1 Start;
                        action @2 doStart;
                    }
                    from Running to Idle {
                        on @1 Stop;
                        guard @2 canStop;
                    }
                }
            }
        "#;
        let result = parse_str(input);
        assert!(result.is_ok(), "Parse failed: {:?}", result.err());
        let ssot_file = result.unwrap();

        assert_eq!(ssot_file.file_id, 0x123456789ABCDEF0);
        assert_eq!(
            ssot_file.package_declaration,
            Some("my.package".to_string())
        );
        assert!(!ssot_file.items.is_empty());

        let machine = &ssot_file.items[0].state_machine.as_ref().unwrap();
        assert_eq!(machine.name.to_string(), "MyMachine");
        assert_eq!(machine.annotations.len(), 1);

        // Verify Context
        assert_eq!(machine.context.len(), 3);
        assert_eq!(machine.context[0].name.to_string(), "counter");
        assert_eq!(machine.context[0].field_type, FieldType::Int32);
        assert_eq!(machine.context[1].name.to_string(), "description");
        assert_eq!(machine.context[1].field_type, FieldType::Text);
        assert_eq!(machine.context[1].ordinal, 1);
        assert_eq!(machine.context[2].name.to_string(), "maybeFlag");
        assert_eq!(machine.context[2].field_type, FieldType::Bool);

        assert_eq!(machine.states.len(), 2);
        assert_eq!(machine.states[0].name.to_string(), "Idle");
        assert!(machine.states[0].entry_actions.is_empty());
        assert!(machine.states[0].exit_actions.is_empty());
        assert_eq!(machine.states[1].name.to_string(), "Running");
        assert_eq!(machine.states[1].entry_actions.len(), 2);
        assert_eq!(machine.states[1].entry_actions[0].to_string(), "action1");
        assert_eq!(machine.states[1].entry_actions[1].to_string(), "action2");
        assert_eq!(machine.states[1].exit_actions.len(), 1);
        assert_eq!(machine.states[1].exit_actions[0].to_string(), "cleanup");

        assert_eq!(machine.events.len(), 3);
        assert_eq!(machine.transitions.len(), 2);
    }

    #[test]
    fn test_missing_file_id() {
        // This input lacks the mandatory file_id
        let input = r#"
            package my_pkg;
            stateMachine Test { states { A@0;} events { event E@0{} } transition from A to A { on @0 E;} }
            "#;
        let result = parse_str(input);
        assert!(result.is_err());
        match result.unwrap_err() {
            // The grammar now requires file_id, so absence is a PestError
            ParseError::PestError(_) => {} // Expect PestError now
            e => panic!("Expected PestError for missing file_id, got {:?}", e),
        }
    }

    #[test]
    fn test_missing_on_in_transition() {
        // Input is now grammatically correct except for the missing 'on' clause
        let input = r#"
             @0x1;
             package my_pkg;
             stateMachine Test {
                 states { A@0; B@1; }
                 events { event E@0{} }
                 // Missing 'on' clause
                 transition from A to B { action @0 some_action; }
             }
             "#;
        let result = parse_str(input);
        assert!(result.is_err());
        // This should ideally be a custom MissingElement error, but might be PestError
        // if the grammar rule structurally requires 'on' before 'action'.
        match result.unwrap_err() {
            ParseError::PestError(_) => {} // Accept PestError for now
            // TODO: Enhance parser logic to detect missing required transition elements like 'on'
            // ParseError::MissingElement(s) => assert!(s.contains("on clause")),
            e => panic!(
                "Expected PestError or MissingElement for missing 'on', got {:?}",
                e
            ),
        }
    }

    #[test]
    fn test_duplicate_state() {
        // Correct syntax for the duplicate check
        let input = r#"
            @0x1;
            package my_pkg;
            stateMachine Test {
                states { A@0; A@1; } // Duplicate state name 'A'
                events { event E@0{} }
                transition from A to A { on @0 E; }
            }
            "#;
        let result = parse_str(input);
        // Expect an error, likely PestError as duplicates aren't specifically handled yet
        assert!(result.is_err());
        match result.unwrap_err() {
            ParseError::PestError(_) => {} // Accept PestError
            // TODO: Enhance parser (`parse_state_enum`) to detect duplicate state names/ordinals
            //       and return ParseError::DuplicateDefinition.
            e => panic!("Expected PestError for duplicate state, got {:?}", e),
        }
    }

    #[test]
    fn test_duplicate_event() {
        // Correct syntax for the duplicate check
        let input = r#"
            @0x1;
            package my_pkg;
            stateMachine Test {
                states { A@0; B@1; }
                events { event E@0{}; event E@1{}; } // Duplicate event name 'E'
                transition from A to B { on @0 E; }
            }
            "#;
        let result = parse_str(input);
        // Expect an error, likely PestError as duplicates aren't specifically handled yet
        assert!(result.is_err());
        match result.unwrap_err() {
            ParseError::PestError(_) => {} // Accept PestError
            // TODO: Enhance parser (`parse_event_definitions`) to detect duplicate event names/ordinals
            //       and return ParseError::DuplicateDefinition.
            e => panic!("Expected PestError for duplicate event, got {:?}", e),
        }
    }

    #[test]
    fn test_parse_annotations_on_items() {
        let input = r#"
        @0xcafe0001;
        stateMachine AnnMachine {
            states {
                $description("Initial idle state.");
                Idle @0;

                $description("Machine is actively running.");
                Running @1;
            }
            events {
                $description("Event to start processing.");
                event Start @0 {
                    $description("User ID initiating the start.");
                    userId @0 : UInt64;

                    $description("Optional config string.");
                    config @1 : Text;
                }

                $description("Event without payload.");
                event Stop @1 {}
            }
            transitions {
                transition from Idle to Running { on @0 Start; }
            }
        }
        "#;
        let result = parse_str(input);
        assert!(result.is_ok(), "Parsing failed: {:?}", result.err());
        let file_ast = result.unwrap();
        let machine = &file_ast.items[1].state_machine.as_ref().unwrap();

        // Check State annotations
        let idle_state = machine.states.iter().find(|s| s.name == "Idle").unwrap();
        assert_eq!(idle_state.annotations.len(), 1);
        assert_eq!(idle_state.annotations[0].name, "description");
        assert_eq!(
            idle_state.annotations[0].value,
            Some(AnnotationValue::StringLiteral(
                "Initial idle state.".to_string()
            ))
        );

        let running_state = machine.states.iter().find(|s| s.name == "Running").unwrap();
        assert_eq!(running_state.annotations.len(), 1);
        assert_eq!(running_state.annotations[0].name, "description");
        assert_eq!(
            running_state.annotations[0].value,
            Some(AnnotationValue::StringLiteral(
                "Machine is actively running.".to_string()
            ))
        );

        // Check Event and Field annotations
        let start_event = machine.events.iter().find(|e| e.name == "Start").unwrap();
        assert_eq!(start_event.annotations.len(), 1);
        assert_eq!(start_event.annotations[0].name, "description");
        assert_eq!(
            start_event.annotations[0].value,
            Some(AnnotationValue::StringLiteral(
                "Event to start processing.".to_string()
            ))
        );

        let userid_field = start_event
            .fields
            .iter()
            .find(|f| f.name == "userId")
            .unwrap();
        assert_eq!(userid_field.annotations.len(), 1);
        assert_eq!(userid_field.annotations[0].name, "description");
        assert_eq!(
            userid_field.annotations[0].value,
            Some(AnnotationValue::StringLiteral(
                "User ID initiating the start.".to_string()
            ))
        );

        let config_field = start_event
            .fields
            .iter()
            .find(|f| f.name == "config")
            .unwrap();
        assert_eq!(config_field.annotations.len(), 1);
        assert_eq!(config_field.annotations[0].name, "description");
        assert_eq!(
            config_field.annotations[0].value,
            Some(AnnotationValue::StringLiteral(
                "Optional config string.".to_string()
            ))
        );

        let stop_event = machine.events.iter().find(|e| e.name == "Stop").unwrap();
        assert_eq!(stop_event.annotations.len(), 1);
        assert_eq!(stop_event.annotations[0].name, "description");
        assert_eq!(
            stop_event.annotations[0].value,
            Some(AnnotationValue::StringLiteral(
                "Event without payload.".to_string()
            ))
        );
    }

    // #[test]
    // fn test_parse_from_file() {
    //     // Create a temporary directory
    //     let dir = tempdir().unwrap();
    //     let file_path = dir.path().join("test.ssot");
    //     let mut file = File::create(&file_path).unwrap();
    //
    //     // Read the content of the actual spec file relative to the workspace root
    //     // Ensure the test runner executes from a context where this relative path is valid,
    //     // typically the workspace root or the crate root.
    //     let input_content = fs::read_to_string("../../fsm-example/spec/my_fsm.ssot")
    //         .expect("Failed to read spec file. Ensure test is run from workspace/crate root.");
    //
    //     // Write the content to the temporary file
    //     writeln!(file, "{}", input_content).unwrap();
    //
    //     // Use parse_file which handles reading the file content
    //     let result = parse_file(&file_path);
    //
    //     // Check if parsing was successful
    //     assert!(result.is_ok(), "{:?}", result.unwrap_err());
    //
    //     // Further assertions on the parsed AST (file_ast)
    //     let file_ast = result.unwrap();
    //     assert_eq!(file_ast.state_machines.len(), 1);
    //     let machine = file_ast.state_machines.first().unwrap();
    //     assert_eq!(machine.name.to_string(), "LightSwitch");
    //     assert_eq!(machine.states.len(), 2);
    //     assert_eq!(machine.events.len(), 3);
    //     assert_eq!(machine.transitions.len(), 4);
    // }
}
