#![allow(clippy::empty_line_after_doc_comments)]

//! # Finite State Machine Code Generator (`fsm-codegen`)
//!
//! This crate takes the Abstract Syntax Tree (AST) generated by `fsm-dsl`
//! (specifically `SsotFile` and `StateMachine` structs) and generates
//! source code for various target languages and formats.
//!
//! The primary goal is to automate the creation of state machine implementations
//! and definitions based on the single source of truth provided by `.ssot` files.
//!
//! ## Supported Targets:
//!
//! *   **Rust:** Generates Rust enums for states and events, a struct for the machine,
//!     a `Callbacks` trait for user-defined actions/guards, and the core transition logic.
//!     (See `generate_rust_code`)
//! *   **Cap'n Proto:** Generates `.capnp` schema files defining the structure of states,
//!     events, and payloads, enabling type-safe serialization. (See `generate_capnp_schema`)
//! *   **TypeScript:** Generates TypeScript type definitions (interfaces, type aliases, discriminated unions)
//!     for states, events, and payloads, suitable for frontend or Node.js applications.
//!     (See `generate_typescript_types`)
//! *   **XState:** Generates TypeScript configuration objects compatible with the XState v5 library,
//!     allowing visualization and execution using XState tools. (See `generate_xstate_machine`)
//! *   **SCXML:** Generates State Chart XML documents, a standard format for describing state machines.
//!     (See `generate_scxml`)
//!
//! ## Usage
//!
//! Typically, this crate is used within a `build.rs` script. The script would:
//! 1. Parse a `.ssot` file using `fsm_dsl::parser::parse_file`.
//! 2. Iterate through the resulting `StateMachine` definitions.
//! 3. Call the relevant `generate_*` functions from this crate.
//! 4. Write the generated code (returned as a `String`) to the appropriate output files
//!    (often determined by annotations like `$rust_out` in the `.ssot` file).
//!
//! ```no_run
//! // Example build.rs snippet
//! use fsm_dsl::parser::parse_file;
//! use fsm_codegen::{generate_rust_code, generate_typescript_types, CodegenError};
//! use std::fs;
//! use std::path::PathBuf;
//! use fsm_dsl::ast::{AnnotationValue, SsotFile};
//!
//! fn find_output_dir(ssot_ast: &SsotFile, machine_ast: &fsm_dsl::ast::StateMachine, annotation_name: &str, default_dir: &str) -> PathBuf {
//!     // Simplified logic: check machine annotations, then file annotations, then use default
//!     let path_str = machine_ast.annotations.iter()
//!         .find(|a| a.name == annotation_name)
//!         .and_then(|a| a.value.as_ref())
//!         .or_else(|| ssot_ast.top_level_annotations.iter()
//!             .find(|a| a.name == annotation_name)
//!             .and_then(|a| a.value.as_ref()))
//!         .and_then(|v| match v {
//!             AnnotationValue::StringLiteral(s) => Some(s.as_str()),
//!             _ => None,
//!         })
//!         .unwrap_or(default_dir);
//!     PathBuf::from(path_str)
//! }
//!
//! fn main() -> Result<(), Box<dyn std::error::Error>> {
//!     let ssot_path = "spec/my_fsm.ssot";
//!     println!("cargo:rerun-if-changed={}", ssot_path);
//!
//!     let ssot_ast = parse_file(ssot_path).expect("Failed to parse .ssot file");
//!
//!     for machine_ast in &ssot_ast.state_machines {
//!         // Generate Rust
//!         let rust_out_dir = find_output_dir(&ssot_ast, machine_ast, "rust_out", "src/generated");
//!         let rust_code = generate_rust_code(machine_ast)?;
//!         let rust_file_name = format!("{}.rs", machine_ast.name.to_string().to_lowercase()); // Example naming
//!         let rust_path = rust_out_dir.join(rust_file_name);
//!         fs::create_dir_all(&rust_out_dir)?;
//!         fs::write(&rust_path, rust_code)?;
//!         println!("Generated Rust code at: {:?}", rust_path);
//!
//!         // Generate TypeScript (if annotation exists)
//!         if let Some(ts_out_dir) = find_output_dir(&ssot_ast, machine_ast, "ts_out", "").strip_prefix("./").ok() {
//!             if !ts_out_dir.as_os_str().is_empty() {
//!                 let ts_code = generate_typescript_types(machine_ast)?;
//!                 let ts_file_name = format!("{}.types.ts", machine_ast.name);
//!                 let ts_path = PathBuf::from(ts_out_dir).join(ts_file_name);
//!                 fs::create_dir_all(ts_out_dir)?;
//!                 fs::write(&ts_path, ts_code)?;
//!                 println!("Generated TypeScript types at: {:?}", ts_path);
//!             }
//!         }
//!         // ... generate other targets similarly ...
//!     }
//!
//!     Ok(())
//! }
//! ```

use fsm_dsl::ast::{
    // Import directly from the ast module
    Annotation,
    AnnotationValue,
    FieldType,
    SsotFile, // Import SsotFile to access file_id
    StateMachine,
    TransitionElement,
};
use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use std::collections::HashSet;
// Needed for parsing generated code before formatting // For collecting unique guard/action names

pub mod codegen_capnp; // Add new module
pub mod codegen_scxml;
pub mod codegen_ts; // Add new module
pub mod codegen_xstate; // Add new module for XState // Add new module for SCXML

// Helper to find annotation value by name
fn find_annotation_value<'a>(
    annotations: &'a [Annotation],
    name: &str,
) -> Option<&'a AnnotationValue> {
    annotations
        .iter()
        .find(|a| a.name == name)
        .and_then(|a| a.value.as_ref())
}

// Helper to map DSL FieldType to Rust type string
fn map_field_type_to_rust_type(field_type: &FieldType) -> TokenStream {
    match field_type {
        FieldType::Void => quote! { () }, // Use unit type for Void
        FieldType::Bool => quote! { bool },
        FieldType::Int8 => quote! { i8 },
        FieldType::Int16 => quote! { i16 },
        FieldType::Int32 => quote! { i32 },
        FieldType::Int64 => quote! { i64 },
        FieldType::UInt8 => quote! { u8 },
        FieldType::UInt16 => quote! { u16 },
        FieldType::UInt32 => quote! { u32 },
        FieldType::UInt64 => quote! { u64 },
        FieldType::Float32 => quote! { f32 },
        FieldType::Float64 => quote! { f64 },
        FieldType::Text => quote! { String },
        FieldType::Data => quote! { Vec<u8> },
        FieldType::List(inner) => {
            let inner_rust_type = map_field_type_to_rust_type(inner);
            quote! { Vec<#inner_rust_type> }
        }
        FieldType::Identifier(ident) => quote! { #ident }, // Assume identifier is a valid Rust type
    }
}

// Helper function to generate Rust doc comments from annotations
fn generate_rust_doc_comment(annotations: &[Annotation]) -> TokenStream {
    let mut doc_stream = quote! {};
    if let Some(AnnotationValue::StringLiteral(desc)) =
        find_annotation_value(annotations, "description")
    {
        // Generate /// comments directly for compatibility with prettyplease
        let comment_str = desc
            .lines()
            .map(|l| format!("/// {}", l.trim()))
            .collect::<Vec<_>>()
            .join("\n");
        // Parse the string into a TokenStream
        if let Ok(tokens) = syn::parse_str::<TokenStream>(&comment_str) {
            doc_stream.extend(tokens);
        }
        // Fallback or error handling if parsing fails?
    }
    // Add other annotation processing here if needed (e.g., #[deprecated])
    doc_stream
}

/// Generates the aggregated Event enum.
/// Assumes events are simple identifiers for now (no associated data structs yet).
// This function is now superseded by generate_event_enum_and_structs, keep or remove?
// Keeping it for now, but it's not used by the main generate_rust_code function.
/*
fn generate_event_enum(ast: &StateMachine, derive_tokens: &proc_macro2::TokenStream) -> proc_macro2::TokenStream {
    let event_enum_name = format_ident!("Event");
    // Use event names collected by the parser
    let variants = ast.events.iter().map(|event_item| { // event_item is MessageItem
        let event_ident = &event_item.name; // Use the Ident field directly
        // For now, assume events don't carry data, just represent the variant
        quote! { #event_ident }
    });

    quote! {
        #derive_tokens // Use the same derives as State and Machine
        pub enum #event_enum_name {
            #(#variants),*
        }
    }
}
*/

/// Generates the `impl` block for the state machine struct.
fn generate_impl_block(
    ast: &StateMachine,
    callbacks_trait_name: &proc_macro2::Ident,
) -> Result<TokenStream, CodegenError> {
    let machine_struct_name = format_ident!("{}", ast.name);
    let state_enum_name = format_ident!("State");
    let event_enum_name = format_ident!("Event");

    // Find the initial state from the $initial annotation
    let initial_state_ident = find_annotation_value(&ast.annotations, "initial")
        .and_then(|value| match value {
            AnnotationValue::Identifier(ident) => Some(ident), // Expecting Identifier value
            _ => None,
        })
        .ok_or_else(|| CodegenError::AstValidationError(
            "Missing or invalid '$initial' annotation on stateMachine. Expected $initial(StateName);".to_string()
        ))?;

    // Validate that the initial state identifier exists in the defined states
    if !ast.states.iter().any(|s| &s.name == initial_state_ident) {
        return Err(CodegenError::AstValidationError(format!(
            "Initial state '{}' defined in $initial annotation is not a declared state.",
            initial_state_ident
        )));
    }
    let initial_state_assignment = quote! { #state_enum_name::#initial_state_ident };

    // Generate match arms for on_event
    let on_event_match_arms = ast
        .transitions
        .iter()
        .map(|transition| -> Result<TokenStream, CodegenError> {
            let from_state_ident = &transition.from;
            let to_state_ident = &transition.to;

            // Find the 'On' element (should be exactly one per transition)
            let on_element = transition
                .elements
                .iter()
                .find_map(|el| match el {
                    TransitionElement::On { event, .. } => Some(event),
                    _ => None,
                })
                .ok_or_else(|| {
                    CodegenError::AstValidationError(format!(
                        "Transition from {} to {} is missing 'on @N EventName;' element.",
                        from_state_ident, to_state_ident
                    ))
                })?;
            let event_variant_ident = on_element; // This is the Ident from the 'on' clause

            // Check if the event definition exists and if it expects a payload
            let event_ast_item = ast
                .events
                .iter()
                .find(|e| &e.name == event_variant_ident)
                .ok_or_else(|| {
                    CodegenError::AstValidationError(format!(
                        "Event '{}' used in transition but not defined in events block.",
                        event_variant_ident
                    ))
                })?;

            let event_payload_fields = &event_ast_item.fields;
            let event_match_pattern = if event_payload_fields.is_empty() {
                quote! { #event_enum_name::#event_variant_ident }
            } else {
                // Use {..} to ignore fields for now in the match arm pattern
                // Actions/guards will receive the full &Event enum variant
                quote! { #event_enum_name::#event_variant_ident { .. } }
            };

            // Find Guard and Action elements
            let guard_call = transition.elements.iter().find_map(|el| match el {
                TransitionElement::Guard { function, .. } => {
                    // Use the collected guard name directly
                    Some(quote! { self.callbacks.#function(&current_state, &event) })
                }
                _ => None,
            });

            let action_call = transition.elements.iter().find_map(|el| match el {
                TransitionElement::Action { function, .. } => {
                    // Use the collected action name directly
                    // Pass current_state, event, and the target state
                    Some(quote! { self.callbacks.#function(&current_state, &event, &next_state) })
                }
                _ => None,
            });

            // Generate entry/exit action calls if they exist
            let exit_action_calls = ast
                .states
                .iter()
                .find(|s| s.name == *from_state_ident)
                .map_or(quote! {}, |state| {
                    let calls: Vec<TokenStream> = state.exit_actions.iter().map(|action_name| {
                    quote! { self.callbacks.#action_name(&current_state, &event, &next_state); }
                }).collect();
                    quote! { #(#calls)* }
                });
            let entry_action_calls = ast
                .states
                .iter()
                .find(|s| s.name == *to_state_ident)
                .map_or(quote! {}, |state| {
                    let calls: Vec<TokenStream> = state.entry_actions.iter().map(|action_name| {
                    quote! { self.callbacks.#action_name(&current_state, &event, &next_state); }
                }).collect();
                    quote! { #(#calls)* }
                });

            // Construct the match arm logic
            let transition_logic = match (guard_call, action_call) {
                (Some(guard), Some(action)) => quote! {
                    if #guard {
                         #exit_action_calls // Call exit actions before changing state
                         let next_state = #state_enum_name::#to_state_ident;
                         #action // Call transition action
                         #entry_action_calls // Call entry actions after action
                         self.current_state = next_state;
                        return true; // Transition occurred
                    }
                },
                (None, Some(action)) => quote! {
                     #exit_action_calls
                     let next_state = #state_enum_name::#to_state_ident;
                     #action
                     #entry_action_calls
                     self.current_state = next_state;
                    return true;
                },
                (Some(guard), None) => quote! {
                    if #guard {
                        #exit_action_calls
                        let next_state = #state_enum_name::#to_state_ident;
                        #entry_action_calls // Call entry actions even if no transition action
                        self.current_state = next_state;
                        return true;
                    }
                },
                (None, None) => quote! {
                    #exit_action_calls
                    let next_state = #state_enum_name::#to_state_ident;
                    #entry_action_calls
                    self.current_state = next_state;
                    return true;
                },
            };

            // Construct the full match arm for this (state, event) pair
            Ok(quote! {
                (#state_enum_name::#from_state_ident, #event_match_pattern) => {
                    #transition_logic
                    // If guard fails or no transition defined for this specific event variant under this state, fall through
                }
            })
        })
        .collect::<Result<Vec<_>, _>>()?; // Collect Results, propagating CodegenError

    // Generate the `on_event` method
    let on_event_method = quote! {
        /// Processes an event and attempts to transition the state machine.
        /// Returns `true` if a transition occurred, `false` otherwise.
        #[allow(unused_variables)] // event might be unused if no transitions use it directly
        pub fn on_event(&mut self, event: Event) -> bool { // Take event by value
            let current_state = self.current_state.clone(); // Clone current state for callbacks
            match (&self.current_state, &event) { // Match against references
                #(#on_event_match_arms)*
                // Default case: No transition for this state/event combination
                _ => false,
            }
        }
    };

    // Generate the `new` method
    let callbacks_param = quote! { callbacks: C };
    let new_method = quote! {
        /// Creates a new instance of the state machine in its initial state.
        pub fn new(#callbacks_param) -> Self {
            Self {
                current_state: #initial_state_assignment,
                callbacks, // Store the provided callbacks implementation
            }
        }
    };

    // Generate the `current_state` getter method
    let current_state_method = quote! {
        /// Returns the current state.
        pub fn current_state(&self) -> &#state_enum_name {
            &self.current_state
        }
    };

    // Generate the impl block
    let impl_block = quote! {
        impl<C: #callbacks_trait_name> #machine_struct_name<C> { // C requires the trait bound
            #new_method
            #on_event_method
            #current_state_method
        }
    };

    Ok(impl_block)
}

/// Generates the Event enum definition with associated data structs.
fn generate_event_enum_and_structs(ast: &StateMachine, derive_tokens: &TokenStream) -> TokenStream {
    let event_enum_name = format_ident!("Event");
    // Use just "Payload" as the suffix convention
    let payload_suffix = format_ident!("Payload");

    let mut event_structs = Vec::new();
    let variants = ast
        .events
        .iter()
        .map(|event_item| {
            let variant_name = &event_item.name; // Use the Ident directly
            let variant_doc_comment = generate_rust_doc_comment(&event_item.annotations);

            if event_item.fields.is_empty() {
                // Event without payload
                quote! {
                    #variant_doc_comment
                    #variant_name
                }
            } else {
                // Event with payload struct
                // Corrected struct name generation
                let struct_name = format_ident!("{}{}", variant_name, payload_suffix);
                let struct_doc_comment = generate_rust_doc_comment(&event_item.annotations); // Use event doc for struct too?

                let fields = event_item.fields.iter().map(|field| {
                    let field_name = &field.name;
                    let field_type_ts = map_field_type_to_rust_type(&field.field_type);
                    let field_doc_comment = generate_rust_doc_comment(&field.annotations);
                    quote! {
                        #field_doc_comment
                        pub #field_name: #field_type_ts
                    }
                });

                // Generate the payload struct definition
                event_structs.push(quote! {
                    #struct_doc_comment
                    #derive_tokens // Derive traits for payload struct too
                    pub struct #struct_name {
                        #(#fields),*
                    }
                });

                // Generate the enum variant with the payload struct
                quote! {
                    #variant_doc_comment
                    #variant_name(#struct_name)
                }
            }
        })
        .collect::<Vec<_>>(); // Collect variants

    let event_enum_doc_comment = generate_rust_doc_comment(&[]); // TODO: Get annotations for the enum itself?

    quote! {
        // --- Event Payload Structs ---
        #(#event_structs)*

        // --- Event Enum ---
        #event_enum_doc_comment
        #derive_tokens // Use the same derives as State and Machine
        pub enum #event_enum_name {
            #(#variants),*
        }
    }
}

/// Generates Rust code from a StateMachine AST node (from parser).
///
/// # Arguments
///
/// * `ast` - A parsed `StateMachine` from `fsm_dsl::parser`.
///
/// # Returns
///
/// * `Result<String, CodegenError>` - Generated Rust code string, or an error.
pub fn generate_rust_code(ast: &StateMachine) -> Result<String, CodegenError> {
    let state_enum_name = format_ident!("State");
    let machine_struct_name = format_ident!("{}", ast.name); // Use name from AST
    let event_enum_name = format_ident!("Event"); // Consistent event enum name
    let callbacks_trait_name = format_ident!("{}Callbacks", ast.name); // e.g., LightSwitchCallbacks

    let _derive_tokens = quote! { #[derive(Debug, Clone, PartialEq)] };

    // State enum generation
    let state_variants = ast.states.iter().map(|s| {
        let variant_name = format_ident!("{}", s.name);
        let doc_comment = generate_rust_doc_comment(&s.annotations);
        quote! {
            #doc_comment // Doc comment first
            #variant_name
        }
    });
    let state_enum_doc_comment = generate_rust_doc_comment(&[]); // TODO: Get annotations for the enum itself?
    let state_enum_derive = quote! { #[derive(Debug, Clone, PartialEq, Eq, Hash)] }; // Define derive separately
    let state_enum = quote! {
        #state_enum_doc_comment // Doc comment first
        #state_enum_derive // Derive second
        // Add Eq, Hash back if no Float types are used in practice or handled
        pub enum #state_enum_name {
            #(#state_variants),*
        }
    }; // <-- Semicolon added here

    // Event enum and payload struct generation
    let event_derive_tokens = quote! { #[derive(Debug, Clone, PartialEq)] };
    let event_defs = generate_event_enum_and_structs(ast, &event_derive_tokens);

    // Machine struct definition
    let machine_struct_doc_comment = generate_rust_doc_comment(&ast.annotations);
    let machine_struct_derive = quote! { #[derive(Debug, Clone, PartialEq)] }; // Define derive separately
    let machine_struct = quote! {
        #machine_struct_doc_comment // Doc comment first
        #machine_struct_derive // Derive second
        // Use PartialEq only for machine struct if state or other fields contain floats
        pub struct #machine_struct_name<C: #callbacks_trait_name> {
            // Make current_state public for inspection/assertion
            pub current_state: #state_enum_name,
            // Add other fields to the machine struct if needed (e.g., context data)
            callbacks: C,
        }
    };

    // --- Callback Trait Generation ---
    let mut guards: HashSet<&proc_macro2::Ident> = HashSet::new();
    let mut actions: HashSet<&proc_macro2::Ident> = HashSet::new();
    let mut entry_actions: HashSet<&proc_macro2::Ident> = HashSet::new();
    let mut exit_actions: HashSet<&proc_macro2::Ident> = HashSet::new();
    let mut callback_signatures: Vec<TokenStream> = Vec::new();

    // Store mapping from function name to its associated event AST item for signature generation
    let mut callback_event_map: std::collections::HashMap<
        &proc_macro2::Ident,
        Vec<&fsm_dsl::ast::MessageItem>,
    > = std::collections::HashMap::new();

    for transition in &ast.transitions {
        // Find the 'On' element to determine the event type for this transition's callbacks
        let on_element = transition.elements.iter().find_map(|el| match el {
            TransitionElement::On { event, .. } => Some(event),
            _ => None,
        });
        let event_ast_item =
            on_element.and_then(|event_ident| ast.events.iter().find(|e| &e.name == event_ident)); // This is Option<&MessageItem>

        for element in &transition.elements {
            match element {
                TransitionElement::Guard { function, .. } => {
                    if guards.insert(function) {
                        // If newly inserted
                        if let Some(event_def) = event_ast_item {
                            callback_event_map
                                .entry(function)
                                .or_default()
                                .push(event_def);
                        }
                    }
                }
                TransitionElement::Action { function, .. } => {
                    if actions.insert(function) {
                        // If newly inserted
                        if let Some(event_def) = event_ast_item {
                            callback_event_map
                                .entry(function)
                                .or_default()
                                .push(event_def);
                        }
                    }
                }
                _ => {}
            }
        }
    }

    // Collect entry/exit actions from states
    for state in &ast.states {
        for entry_action in &state.entry_actions {
            entry_actions.insert(entry_action);
        }
        for exit_action in &state.exit_actions {
            exit_actions.insert(exit_action);
        }
    }

    // Generate guard signatures
    for guard_fn_ident in &guards {
        // Find the most specific event type if possible, otherwise use generic &Event
        let event_defs = callback_event_map.get(guard_fn_ident);
        let event_type_sig = determine_callback_event_signature(event_defs, &event_enum_name);

        let guard_methods = quote! {
            #[allow(unused_variables)]
            /// Guard condition for transitions: #guard_fn_ident
            fn #guard_fn_ident(&self, current_state: &State, event: #event_type_sig) -> bool {
                eprintln!("[WARN] Guard '{}' not implemented, returning default false.", stringify!(#guard_fn_ident));
                false // Default guard implementation
            }
        };

        callback_signatures.push(guard_methods);
    }

    // Generate action signatures
    for action_fn_ident in &actions {
        // Find the most specific event type if possible, otherwise use generic &Event
        let event_defs = callback_event_map.get(action_fn_ident);
        let event_type_sig = determine_callback_event_signature(event_defs, &event_enum_name);

        let action_methods = quote! {
            #[allow(unused_variables)]
            /// Action executed during transitions or on entry/exit: #action_fn_ident
            fn #action_fn_ident(&mut self, current_state: &State, event: #event_type_sig, next_state: &State) {
                eprintln!("[WARN] Action '{}' not implemented.", stringify!(#action_fn_ident));
                // Default action implementation (no-op)
            }
        };

        callback_signatures.push(action_methods);
    }

    // Generate entry action signatures
    for entry_fn_ident in &entry_actions {
        // Entry actions triggered after state change, takes mutable self
        // TODO: Consider adding context/state reference if needed
        callback_signatures.push(quote! {
            fn #entry_fn_ident(&mut self);
        });
    }

    // Generate exit action signatures
    for exit_fn_ident in &exit_actions {
        // Exit actions triggered before state change, takes mutable self
        // TODO: Consider adding context/state reference if needed
        callback_signatures.push(quote! {
            fn #exit_fn_ident(&mut self);
        });
    }

    let callbacks_trait_doc_comment = generate_rust_doc_comment(&[]); // TODO: Use machine annotations?
    let callbacks_trait = if !guards.is_empty()
        || !actions.is_empty()
        || !entry_actions.is_empty()
        || !exit_actions.is_empty()
    {
        quote! {
            #callbacks_trait_doc_comment
            /// Trait defining the required guard, action, entry, and exit callbacks for the state machine.
            pub trait #callbacks_trait_name {
                #(#callback_signatures)*
            }
        }
    } else {
        quote! {} // No trait if no callbacks
    };

    // Impl block generation (Pass only trait name)
    let impl_block = generate_impl_block(ast, &callbacks_trait_name)?;

    // Generate Default impl
    let default_impl = quote! {
        impl<C: #callbacks_trait_name + Default> Default for #machine_struct_name<C> {
            fn default() -> Self {
                Self::new(C::default()) // Call new with default callbacks
            }
        }
    };

    // Combine all parts
    let combined_code = quote! {
        #state_enum
        #event_defs
        #callbacks_trait
        #machine_struct
        #impl_block
        #default_impl
    };

    // Format the generated code
    let code_str = combined_code.to_string();
    match syn::parse_file(&code_str) {
        Ok(syntax_tree) => Ok(prettyplease::unparse(&syntax_tree)),
        Err(e) => {
            eprintln!("--- Failed to parse generated code ---");
            eprintln!("{}", code_str);
            eprintln!("--- End generated code ---");
            // Manually construct the error variant
            Err(CodegenError::SynParseError(e, code_str))
        }
    }
}

// Helper function to determine the most specific event type signature for a callback
// based on all transitions where it's used. Falls back to generic &Event if types conflict
// or no event context is found.
fn determine_callback_event_signature<'a>(
    event_defs: Option<&'a Vec<&'a fsm_dsl::ast::MessageItem>>,
    event_enum_name: &proc_macro2::Ident,
) -> TokenStream {
    match event_defs {
        Some(defs) if !defs.is_empty() => {
            let first_def = defs[0];
            // Check if all uses agree on whether there's a payload and the payload type name
            let all_agree = defs.iter().all(|d| {
                (d.fields.is_empty() == first_def.fields.is_empty())
                    && (d.fields.is_empty() || d.name == first_def.name) // Check payload name matches if not empty
            });

            if all_agree {
                if first_def.fields.is_empty() {
                    // All uses are for events without payload, use reference to enum
                    quote! { &#event_enum_name }
                } else {
                    // All uses are for the same event with payload, use reference to payload struct
                    // Use the correct payload struct naming convention
                    let payload_suffix = format_ident!("Payload");
                    let payload_struct_name = format_ident!("{}{}", first_def.name, payload_suffix);
                    quote! { &#payload_struct_name }
                }
            } else {
                // Disagreement in payload types, fall back to generic enum reference
                quote! { &#event_enum_name }
            }
        }
        _ => {
            // No event context found or empty list, fall back to generic enum reference
            quote! { &#event_enum_name }
        }
    }
}

/// Generates a Cap'n Proto schema (.capnp) from the FSM AST.
///
/// # Arguments
///
/// * `file_ast` - The parsed `SsotFile` structure (needed for file ID).
/// * `machine_ast` - The specific `StateMachine` structure to generate the schema for.
///
/// # Returns
///
/// A `Result` containing the Cap'n Proto schema string or a `CodegenError`.
pub fn generate_capnp_schema(
    file_ast: &SsotFile, // Updated signature
    machine_ast: &StateMachine,
) -> Result<String, CodegenError> {
    // Use the internal function from the capnp module
    codegen_capnp::generate_capnp_schema_internal(file_ast, machine_ast)
}

/// Generates TypeScript type definitions (.types.ts) from the FSM AST.
///
/// # Arguments
///
/// * `ast` - The parsed `StateMachine` structure.
///
/// # Returns
///
/// A `Result` containing the TypeScript type definition string or a `CodegenError`.
pub fn generate_typescript_types(ast: &StateMachine) -> Result<String, CodegenError> {
    // Use the internal function from the ts module
    codegen_ts::generate_typescript_types_internal(ast)
}

/// Generates an XState machine definition string from the FSM AST.
///
/// # Arguments
/// * `ast` - A reference to the `StateMachine` AST node.
///
/// # Returns
/// A `Result` containing the generated XState machine definition (e.g., as a JS object literal string) or a `CodegenError`.
pub fn generate_xstate_machine(ast: &StateMachine) -> Result<String, CodegenError> {
    // Use the internal function from the xstate module
    codegen_xstate::generate_xstate_machine_internal(ast)
}

/// Generates an SCXML document string from the FSM AST.
///
/// # Arguments
/// * `ast` - A reference to the `StateMachine` AST node.
///
/// # Returns
/// A `Result` containing the generated SCXML document as a `String` or a `CodegenError`.
pub fn generate_scxml(ast: &StateMachine) -> Result<String, CodegenError> {
    // Use the internal function from the scxml module
    codegen_scxml::generate_scxml_internal(ast)
}

// Error type
#[derive(Debug, thiserror::Error)]
pub enum CodegenError {
    #[error(
        "Failed to parse generated code: {0}\n--- Generated Code ---
{1}"
    )]
    SynParseError(syn::Error, String),
    #[error("AST validation error: {0}")]
    AstValidationError(String),
    #[error("Code generation failed: {0}")]
    GenerationError(String),
    #[error("I/O error during code formatting: {0}")]
    FormatIoError(#[from] std::io::Error),
    #[error("Failed to format generated code: {0}")]
    FormatError(String),
    // Potential future errors: IO errors, etc.
}

// Add the From implementation here, once, centrally.
impl From<std::fmt::Error> for CodegenError {
    fn from(err: std::fmt::Error) -> Self {
        CodegenError::GenerationError(format!("Failed to write to string: {}", err))
    }
}

// --- Unit Tests ---
#[cfg(test)]
mod tests {
    use super::*; // Bring parent module's items into scope
    use fsm_dsl::parser::parse_str; // Import the CORRECT parser function
                                    // Import necessary AST types for helper functions
    use fsm_dsl::ast::{
        Annotation, AnnotationValue, FieldDef, FieldType, MessageItem, StateItem, StateMachine,
        TransitionElement, TransitionItem,
    };
    use syn::parse_file as syn_parse_file; // Import for code parsing in tests

    // --- Define shared constants for tests ---
    const ANNOTATED_MACHINE_SSOT: &str = r#"
@0xdeadbeefcafe0001;

$description("This is the main machine.");
stateMachine AnnotatedMachine {
    $initial(Idle);
    states {
        $description("Waiting state.");
        Idle @0;
        $description("Active state.");
        Running @1;
    }
    events {
        $description("Starts the machine.");
        event Start @0 {
            $description("The user ID.");
            userId @0 : UInt64;
        }
        $description("Stops the machine.");
        event Stop @1; // Use semicolon instead of {} for empty event
    }
    transitions {
        transition StartIdle from Idle to Running { on @0 Start; }
        transition StopRunning from Running to Idle { on @1 Stop; }
    }
}
"#;

    // Helper function to create identifiers for tests
    fn ident(s: &str) -> proc_macro2::Ident {
        proc_macro2::Ident::new(s, proc_macro2::Span::call_site())
    }

    // Helper to create a basic StateMachine AST for testing
    fn create_test_ast() -> StateMachine {
        StateMachine {
            name: ident("TestMachine"),
            annotations: vec![Annotation {
                name: ident("initial"),
                value: Some(AnnotationValue::Identifier(ident("Idle"))),
            }],
            events: vec![
                MessageItem {
                    name: ident("Event1"),
                    ordinal: 0, // Use u64 directly
                    annotations: vec![],
                    fields: vec![],
                },
                MessageItem {
                    name: ident("Event2"),
                    ordinal: 1, // Use u64 directly
                    annotations: vec![],
                    fields: vec![],
                },
                MessageItem {
                    name: ident("EventWithPayload"),
                    ordinal: 2, // Use u64 directly
                    annotations: vec![],
                    fields: vec![FieldDef {
                        name: ident("data"),
                        ordinal: 0, // Use u64 directly
                        annotations: vec![],
                        field_type: FieldType::UInt32,
                    }],
                },
            ],
            states: vec![
                StateItem {
                    name: ident("Idle"),
                    ordinal: 0, // Use u64 directly
                    annotations: vec![],
                    entry_actions: vec![],
                    exit_actions: vec![],
                },
                StateItem {
                    name: ident("Active"),
                    ordinal: 1, // Use u64 directly
                    annotations: vec![],
                    entry_actions: vec![],
                    exit_actions: vec![],
                },
            ],
            transitions: vec![
                TransitionItem {
                    name: Some(ident("T1")), // Wrap name in Some
                    from: ident("Idle"),
                    to: ident("Active"),
                    annotations: vec![],
                    elements: vec![TransitionElement::On {
                        ordinal: 0,
                        event: ident("Event1"),
                    }], // Use u64 directly
                },
                TransitionItem {
                    name: Some(ident("T2")), // Wrap name in Some
                    from: ident("Active"),
                    to: ident("Idle"),
                    annotations: vec![],
                    elements: vec![TransitionElement::On {
                        ordinal: 1,
                        event: ident("Event2"),
                    }], // Use u64 directly
                },
                TransitionItem {
                    name: Some(ident("T3WithAction")), // Wrap name in Some
                    from: ident("Idle"),
                    to: ident("Active"),
                    annotations: vec![],
                    elements: vec![
                        TransitionElement::On {
                            ordinal: 2,
                            event: ident("EventWithPayload"),
                        }, // Use u64 directly
                        TransitionElement::Action {
                            ordinal: 0,
                            function: ident("do_something"),
                        }, // Use u64 directly
                    ],
                },
            ],
            context: vec![], // Add missing context field
        }
    }

    // Helper to parse and format code for comparison
    fn parse_and_format(code: &str) -> String {
        let parsed_file = syn_parse_file(code).expect("Failed to parse generated code");
        prettyplease::unparse(&parsed_file)
    }

    #[test]
    fn generates_basic_structures() {
        let ast = create_test_ast();
        let result = generate_rust_code(&ast); // Assuming generate_rust_code takes &StateMachine
        assert!(result.is_ok(), "Rust generation failed");
        let code = result.unwrap();
        let formatted_code = parse_and_format(&code);

        // Basic checks (adjust based on actual generation)
        assert!(formatted_code.contains("pub enum State"));
        assert!(formatted_code.contains("Idle"));
        assert!(formatted_code.contains("Active"));
        assert!(formatted_code.contains("pub enum Event"));
        assert!(formatted_code.contains("Event1"));
        assert!(formatted_code.contains("Event2"));
        assert!(formatted_code.contains("pub struct EventWithPayloadPayload")); // Check payload struct
        assert!(formatted_code.contains("EventWithPayload(EventWithPayloadPayload)")); // Check enum variant with payload
        assert!(formatted_code.contains("pub struct TestMachine"));
    }

    #[test]
    fn generates_impl_block_and_new() {
        let ast = create_test_ast();
        let result = generate_rust_code(&ast);
        assert!(result.is_ok(), "Rust generation failed");
        let code = result.unwrap();
        let formatted_code = parse_and_format(&code);

        assert!(formatted_code.contains("impl TestMachine"));
        assert!(formatted_code.contains("pub fn new() -> Self"));
        assert!(formatted_code.contains("current_state: State::Idle")); // Check initial state assignment
        assert!(formatted_code.contains("impl Default for TestMachine"));
        assert!(formatted_code.contains("Self::new()"));
    }

    #[test]
    fn generates_on_event_method_with_transitions() {
        let ast = create_test_ast();
        let result = generate_rust_code(&ast);
        assert!(result.is_ok(), "Rust generation failed");
        let code = result.unwrap();
        let formatted_code = parse_and_format(&code);

        assert!(
            formatted_code.contains("pub fn on_event(self, event: Event) -> Result<Self, String>")
        );
        assert!(formatted_code.contains("match (&self.current_state, &event)"));
        // Updated checks for bool return type and different structure
        assert!(formatted_code.contains("(State::Idle, &Event::Event1) =>")); // Check matching reference
        assert!(formatted_code.contains("self.current_state = State::Active;"));
        assert!(formatted_code.contains("return true;"));
        assert!(formatted_code.contains("(State::Active, &Event::Event2) =>"));
        assert!(formatted_code.contains("self.current_state = State::Idle;"));
        assert!(formatted_code.contains("(State::Idle, &Event::EventWithPayload { .. }) =>")); // Check payload matching
        assert!(formatted_code
            .contains("self.callbacks.do_something(&current_state, &event, &next_state);")); // Check action call
        assert!(formatted_code.contains("_ => false")); // Default case
    }

    #[test]
    fn generates_guard_and_action_placeholders_module() {
        // Need an AST with guards/actions
        let ast_with_callbacks = StateMachine {
            // Simplified AST for this test
            name: ident("CallbackMachine"),
            annotations: vec![Annotation {
                name: ident("initial"),
                value: Some(AnnotationValue::Identifier(ident("S1"))),
            }],
            events: vec![MessageItem {
                name: ident("E1"),
                ordinal: 0,
                annotations: vec![],
                fields: vec![],
            }], // Use u64 directly
            states: vec![
                StateItem {
                    name: ident("S1"),
                    ordinal: 0,
                    annotations: vec![],
                    entry_actions: vec![],
                    exit_actions: vec![],
                }, // Use u64 directly
                StateItem {
                    name: ident("S2"),
                    ordinal: 1,
                    annotations: vec![],
                    entry_actions: vec![],
                    exit_actions: vec![],
                },
            ], // Use u64 directly
            transitions: vec![TransitionItem {
                name: Some(ident("T1")), // Wrap name in Some
                from: ident("S1"),
                to: ident("S2"),
                annotations: vec![],
                elements: vec![
                    TransitionElement::On {
                        ordinal: 0,
                        event: ident("E1"),
                    }, // Use u64 directly
                    TransitionElement::Guard {
                        ordinal: 0,
                        function: ident("can_transition"),
                    }, // Use u64 directly
                    TransitionElement::Action {
                        ordinal: 1,
                        function: ident("perform_action"),
                    }, // Use u64 directly
                ],
            }],
            context: vec![], // Add missing context field
        };
        let result = generate_rust_code(&ast_with_callbacks);
        assert!(result.is_ok(), "Rust generation failed");
        let code = result.unwrap();
        let formatted_code = parse_and_format(&code);

        println!(
            "-- CallbackMachine Code --\n{}\n-- End CallbackMachine Code --",
            formatted_code
        );

        // Check trait definition
        assert!(formatted_code.contains("pub trait CallbackMachineCallbacks"));
        // Check guard with default impl
        assert!(formatted_code
            .contains("fn can_transition(&self, current_state: &State, event: &Event) -> bool {"));
        assert!(
            formatted_code.contains("eprintln!(\"[WARN] Guard 'can_transition' not implemented")
        );
        assert!(formatted_code.contains("false"));
        // Check action with default impl
        assert!(formatted_code.contains("fn perform_action(&mut self, current_state: &State, event: &Event, next_state: &State) {"));
        assert!(
            formatted_code.contains("eprintln!(\"[WARN] Action 'perform_action' not implemented")
        );
    }

    #[test]
    fn handles_no_transitions_or_callbacks() {
        let simple_ast = StateMachine {
            name: ident("SimpleMachine"),
            annotations: vec![Annotation {
                name: ident("initial"),
                value: Some(AnnotationValue::Identifier(ident("OnlyState"))),
            }],
            events: vec![MessageItem {
                name: ident("DummyEvent"),
                ordinal: 0,
                annotations: vec![],
                fields: vec![],
            }], // Use u64 directly
            states: vec![StateItem {
                name: ident("OnlyState"),
                ordinal: 0,
                annotations: vec![],
                entry_actions: vec![],
                exit_actions: vec![],
            }], // Use u64 directly
            transitions: vec![], // No transitions
            context: vec![],     // Add missing context field
        };
        let result = generate_rust_code(&simple_ast);
        assert!(result.is_ok(), "Rust generation failed");
        let code = result.unwrap();
        let formatted_code = parse_and_format(&code);

        // Check that impl block is generated, but on_event might be simple
        assert!(formatted_code.contains("impl SimpleMachine"));
        // Check on_event signature
        assert!(formatted_code.contains("pub fn on_event(&mut self, event: Event) -> bool"));
        assert!(formatted_code.contains("match (&self.current_state, &event)"));
        // Should likely only contain the default arm if no transitions
        assert!(formatted_code.contains("_ => false"));
        // Check that no callback trait is generated
        assert!(!formatted_code.contains("pub trait SimpleMachineCallbacks"));
    }

    #[test]
    fn generates_current_state_getter() {
        let ast = create_test_ast();
        let result = generate_rust_code(&ast);
        assert!(result.is_ok(), "Rust generation failed");
        let code = result.unwrap();
        let formatted_code = parse_and_format(&code);

        assert!(formatted_code.contains("pub fn current_state(&self) -> &State"));
        assert!(formatted_code.contains("&self.current_state"));
    }

    // --- Tests using ANNOTATED_MACHINE_SSOT ---

    #[test]
    fn generates_rust_code_with_doc_comments() {
        let ast = parse_str(ANNOTATED_MACHINE_SSOT).unwrap();
        let machine = &ast.state_machines[0];
        let _code = generate_rust_code(machine).unwrap();
        let formatted_code = parse_and_format(&_code);
        assert!(formatted_code.contains(
            "#[derive(Debug, Clone, PartialEq, Eq, Hash)]\\n/// Waiting state.\\npub enum State"
        ));
        assert!(formatted_code.contains("/// Waiting state.\\n    Idle,"));
        assert!(formatted_code.contains("/// Active state.\\n    Running,"));
        assert!(formatted_code.contains("/// Starts the machine.\\n#[derive(Debug, Clone, PartialEq)]\\npub struct StartPayload")); // Adjusted name
        assert!(formatted_code.contains("/// The user ID.\\n    pub userId: u64,"));
        assert!(formatted_code.contains("/// Starts the machine.\\n    Start(StartPayload),")); // Adjusted name
        assert!(formatted_code.contains("/// Stops the machine.\\n    Stop,"));
        assert!(formatted_code.contains("/// This is the main machine.\\n#[derive(Debug, Clone, PartialEq)]\\npub struct AnnotatedMachine"));
        assert!(formatted_code.contains("impl AnnotatedMachine"));
        assert!(formatted_code.contains("/// Creates a new instance"));
        assert!(formatted_code.contains("/// Processes an event"));
        assert!(formatted_code.contains("/// Returns the current state."));
        assert!(formatted_code.contains("impl Default for AnnotatedMachine"));
    }

    #[test]
    fn generates_capnp_schema_with_comments() {
        let ast = parse_str(ANNOTATED_MACHINE_SSOT).unwrap();
        let machine = &ast.state_machines[0];
        let result = generate_capnp_schema(&ast, machine);
        assert!(
            result.is_ok(),
            "Capnp generation failed: {:?}",
            result.err()
        );
        let _schema = result.unwrap();
        assert!(_schema.contains("@0xdeadbeefcafe0001;"));
        assert!(_schema.contains("# This is the main machine."));
        assert!(_schema.contains("enum State @0"));
        assert!(_schema.contains("# Waiting state.\\n  Idle @0;"));
        assert!(_schema.contains("# Active state.\\n  Running @1;"));
        assert!(_schema.contains("struct StartPayload @2")); // Adjusted name
        assert!(_schema.contains("# The user ID.\\n  userId @0 :UInt64;"));
        assert!(_schema.contains("union Event @1"));
        assert!(_schema.contains("# Starts the machine.\\n  Start @0 :StartPayload;")); // Adjusted name
        assert!(_schema.contains("# Stops the machine.\\n  Stop @1 :Void;"));
    }

    #[test]
    fn generates_typescript_types_with_jsdoc() {
        let ast = parse_str(ANNOTATED_MACHINE_SSOT).unwrap();
        let machine = &ast.state_machines[0];
        let _types = generate_typescript_types(machine).unwrap();
        assert!(_types.contains("/**\n * This is the main machine.\n */"));
        assert!(_types.contains("export interface Context {"));
        assert!(_types.contains("export type State ="));
        assert!(_types.contains("/**\n   * Waiting state.\n   */\n\"Idle\""));
        assert!(_types.contains("|   /**\n   * Active state.\n   */\n\"Running\""));
        assert!(_types.contains("/**\n * Starts the machine.\n */"));
        assert!(_types.contains("export interface StartPayload {")); // Adjusted name
        assert!(_types.contains("/**\n   * The user ID.\n   */\n  userId: bigint;"));
        assert!(_types.contains("export type Event ="));
        assert!(_types.contains(
            "/**\n   * Starts the machine.\n   */\n   { type: \"Start\", payload: StartPayload }" // Adjusted name
        ));
        assert!(_types.contains("/**\n   * Stops the machine.\n   */\n|  { type: \"Stop\" };"));
    }
}
