#![allow(clippy::empty_line_after_doc_comments)]

//! # Finite State Machine Code Generator (`fsm-codegen`)
//!
//! This crate takes the Abstract Syntax Tree (AST) generated by `fsm-dsl`
//! (specifically `SsotFile` and `StateMachine` structs) and generates
//! source code for various target languages and formats.
//!
//! The primary goal is to automate the creation of state machine implementations
//! and definitions based on the single source of truth provided by `.ssot` files.
//!
//! ## Supported Targets:
//!
//! *   **Rust:** Generates Rust enums for states and events, a struct for the machine,
//!     a `Callbacks` trait for user-defined actions/guards, and the core transition logic.
//!     (See `generate_rust_code`)
//! *   **Cap'n Proto:** Generates `.capnp` schema files defining the structure of states,
//!     events, and payloads, enabling type-safe serialization. (See `generate_capnp_schema`)
//! *   **TypeScript:** Generates TypeScript type definitions (interfaces, type aliases, discriminated unions)
//!     for states, events, and payloads, suitable for frontend or Node.js applications.
//!     (See `generate_typescript_types`)
//! *   **XState:** Generates TypeScript configuration objects compatible with the XState v5 library,
//!     allowing visualization and execution using XState tools. (See `generate_xstate_machine`)
//! *   **SCXML:** Generates State Chart XML documents, a standard format for describing state machines.
//!     (See `generate_scxml`)
//!
//! ## Usage
//!
//! Typically, this crate is used within a `build.rs` script. The script would:
//! 1. Parse a `.ssot` file using `fsm_dsl::parser::parse_file`.
//! 2. Iterate through the resulting `StateMachine` definitions.
//! 3. Call the relevant `generate_*` functions from this crate.
//! 4. Write the generated code (returned as a `String`) to the appropriate output files
//!    (often determined by annotations like `$rust_out` in the `.ssot` file).
//!
//! ```no_run
//! // Example build.rs snippet
//! use fsm_dsl::parser::parse_file;
//! use fsm_codegen::{generate_rust_code, generate_typescript_types, CodegenError};
//! use std::fs;
//! use std::path::PathBuf;
//! use fsm_dsl::ast::{AnnotationValue, SsotFile};
//!
//! fn find_output_dir(ssot_ast: &SsotFile, machine_ast: &fsm_dsl::ast::StateMachine, annotation_name: &str, default_dir: &str) -> PathBuf {
//!     // Simplified logic: check machine annotations, then file annotations, then use default
//!     let path_str = machine_ast.annotations.iter()
//!         .find(|a| a.name == annotation_name)
//!         .and_then(|a| a.value.as_ref())
//!         .or_else(|| ssot_ast.top_level_annotations.iter()
//!             .find(|a| a.name == annotation_name)
//!             .and_then(|a| a.value.as_ref()))
//!         .and_then(|v| match v {
//!             AnnotationValue::StringLiteral(s) => Some(s.as_str()),
//!             _ => None,
//!         })
//!         .unwrap_or(default_dir);
//!     PathBuf::from(path_str)
//! }
//!
//! fn main() -> Result<(), Box<dyn std::error::Error>> {
//!     let ssot_path = "spec/my_fsm.ssot";
//!     println!("cargo:rerun-if-changed={}", ssot_path);
//!
//!     let ssot_ast = parse_file(ssot_path).expect("Failed to parse .ssot file");
//!
//!     for machine_ast in &ssot_ast.state_machines {
//!         // Generate Rust
//!         let rust_out_dir = find_output_dir(&ssot_ast, machine_ast, "rust_out", "src/generated");
//!         let rust_code = generate_rust_code(machine_ast)?;
//!         let rust_file_name = format!("{}.rs", machine_ast.name.to_string().to_lowercase()); // Example naming
//!         let rust_path = rust_out_dir.join(rust_file_name);
//!         fs::create_dir_all(&rust_out_dir)?;
//!         fs::write(&rust_path, rust_code)?;
//!         println!("Generated Rust code at: {:?}", rust_path);
//!
//!         // Generate TypeScript (if annotation exists)
//!         if let Some(ts_out_dir) = find_output_dir(&ssot_ast, machine_ast, "ts_out", "").strip_prefix("./").ok() {
//!             if !ts_out_dir.as_os_str().is_empty() {
//!                 let ts_code = generate_typescript_types(machine_ast)?;
//!                 let ts_file_name = format!("{}.types.ts", machine_ast.name);
//!                 let ts_path = PathBuf::from(ts_out_dir).join(ts_file_name);
//!                 fs::create_dir_all(ts_out_dir)?;
//!                 fs::write(&ts_path, ts_code)?;
//!                 println!("Generated TypeScript types at: {:?}", ts_path);
//!             }
//!         }
//!         // ... generate other targets similarly ...
//!     }
//!
//!     Ok(())
//! }
//! ```

use fsm_dsl::ast::{
    // Import directly from the ast module
    Annotation,
    AnnotationValue,
    FieldType,
    SsotFile, // Import SsotFile to access file_id
    StateMachine,
    TransitionElement,
};
use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use std::collections::HashSet;
// Needed for parsing generated code before formatting // For collecting unique guard/action names

pub mod codegen_capnp; // Add new module
pub mod codegen_scxml;
pub mod codegen_ts; // Add new module
pub mod codegen_xstate; // Add new module for XState // Add new module for SCXML

// Helper to find annotation value by name
fn find_annotation_value<'a>(
    annotations: &'a [Annotation],
    name: &str,
) -> Option<&'a AnnotationValue> {
    annotations
        .iter()
        .find(|a| a.name == name)
        .and_then(|a| a.value.as_ref())
}

// Helper to map DSL FieldType to Rust type string
fn map_field_type_to_rust_type(field_type: &FieldType) -> TokenStream {
    match field_type {
        FieldType::Void => quote! { () }, // Use unit type for Void
        FieldType::Bool => quote! { bool },
        FieldType::Int8 => quote! { i8 },
        FieldType::Int16 => quote! { i16 },
        FieldType::Int32 => quote! { i32 },
        FieldType::Int64 => quote! { i64 },
        FieldType::UInt8 => quote! { u8 },
        FieldType::UInt16 => quote! { u16 },
        FieldType::UInt32 => quote! { u32 },
        FieldType::UInt64 => quote! { u64 },
        FieldType::Float32 => quote! { f32 },
        FieldType::Float64 => quote! { f64 },
        FieldType::Text => quote! { String },
        FieldType::Data => quote! { Vec<u8> },
        FieldType::List(inner) => {
            let inner_rust_type = map_field_type_to_rust_type(inner);
            quote! { Vec<#inner_rust_type> }
        }
        FieldType::Identifier(ident) => quote! { #ident }, // Assume identifier is a valid Rust type
    }
}

// Helper function to generate Rust doc comments from annotations
fn generate_rust_doc_comment(annotations: &[Annotation]) -> TokenStream {
    let mut doc_stream = quote! {};
    if let Some(AnnotationValue::StringLiteral(desc)) =
        find_annotation_value(annotations, "description")
    {
        // Generate /// comments directly for compatibility with prettyplease
        let comment_str = desc
            .lines()
            .map(|l| format!("/// {}", l.trim()))
            .collect::<Vec<_>>()
            .join("\n");
        // Parse the string into a TokenStream
        if let Ok(tokens) = syn::parse_str::<TokenStream>(&comment_str) {
            doc_stream.extend(tokens);
        }
        // Fallback or error handling if parsing fails?
    }
    // Add other annotation processing here if needed (e.g., #[deprecated])
    doc_stream
}

/// Generates the `impl` block for the state machine struct.
fn generate_impl_block(
    ast: &StateMachine,
    callbacks_trait_name: &proc_macro2::Ident,
) -> Result<TokenStream, CodegenError> {
    let machine_struct_name = format_ident!("{}", ast.name);
    let state_enum_name = format_ident!("State");
    let event_enum_name = format_ident!("Event");

    // Find the initial state from the $initial annotation
    let initial_state_ident = find_annotation_value(&ast.annotations, "initial")
        .and_then(|value| match value {
            AnnotationValue::Identifier(ident) => Some(ident), // Expecting Identifier value
            _ => None,
        })
        .ok_or_else(|| CodegenError::AstValidationError(
            "Missing or invalid '$initial' annotation on stateMachine. Expected $initial(StateName);".to_string()
        ))?;

    // Validate that the initial state identifier exists in the defined states
    if !ast.states.iter().any(|s| &s.name == initial_state_ident) {
        return Err(CodegenError::AstValidationError(format!(
            "Initial state '{}' defined in $initial annotation is not a declared state.",
            initial_state_ident
        )));
    }
    let initial_state_assignment = quote! { #state_enum_name::#initial_state_ident };

    // Generate match arms for on_event
    let on_event_match_arms = ast
        .transitions
        .iter()
        .map(|transition| -> Result<TokenStream, CodegenError> {
            let from_state_ident = &transition.from;
            let to_state_ident = &transition.to;

            // Find the 'On' element (should be exactly one per transition)
            let on_element = transition
                .elements
                .iter()
                .find_map(|el| match el {
                    TransitionElement::On { event, .. } => Some(event),
                    _ => None,
                })
                .ok_or_else(|| {
                    CodegenError::AstValidationError(format!(
                        "Transition from {} to {} is missing 'on @N EventName;' element.",
                        from_state_ident, to_state_ident
                    ))
                })?;
            let event_variant_ident = on_element; // This is the Ident from the 'on' clause

            // Check if the event definition exists and if it expects a payload
            let event_ast_item = ast
                .events
                .iter()
                .find(|e| &e.name == event_variant_ident)
                .ok_or_else(|| {
                    CodegenError::AstValidationError(format!(
                        "Event '{}' used in transition but not defined in events block.",
                        event_variant_ident
                    ))
                })?;

            let event_payload_fields = &event_ast_item.fields;
            let event_match_pattern = if event_payload_fields.is_empty() {
                quote! { #event_enum_name::#event_variant_ident }
            } else {
                // Use {..} to ignore fields for now in the match arm pattern
                // Actions/guards will receive the full &Event enum variant
                quote! { #event_enum_name::#event_variant_ident { .. } }
            };

            // Find Guard and Action elements
            let guard_call = transition.elements.iter().find_map(|el| match el {
                TransitionElement::Guard { function, .. } => {
                    // Note: current_state is cloned before the match in on_event
                    Some(quote! { self.callbacks.#function(&current_state, &event) })
                }
                _ => None,
            });

            let action_call = transition.elements.iter().find_map(|el| match el {
                TransitionElement::Action { function, .. } => {
                    // Note: current_state is cloned before the match in on_event
                    Some(quote! { self.callbacks.#function(&current_state, &event, &next_state) })
                }
                _ => None,
            });

            // Generate entry/exit action calls if they exist
            let exit_action_calls = ast
                .states
                .iter()
                .find(|s| s.name == *from_state_ident)
                .map_or(quote! {}, |state| {
                    let calls: Vec<TokenStream> = state.exit_actions.iter().map(|action_name| {
                    // Note: current_state is cloned before the match in on_event
                    quote! { self.callbacks.#action_name(&current_state, &event, &next_state); }
                }).collect();
                    quote! { #(#calls)* }
                });
            let entry_action_calls = ast
                .states
                .iter()
                .find(|s| s.name == *to_state_ident)
                .map_or(quote! {}, |state| {
                    let calls: Vec<TokenStream> = state.entry_actions.iter().map(|action_name| {
                    // Note: current_state is cloned before the match in on_event
                    quote! { self.callbacks.#action_name(&current_state, &event, &next_state); }
                }).collect();
                    quote! { #(#calls)* }
                });

            // Construct the match arm logic
            let transition_logic = match (guard_call, action_call) {
                (Some(guard), Some(action)) => quote! {
                    if #guard {
                         #exit_action_calls // Call exit actions before changing state
                         let next_state = #state_enum_name::#to_state_ident;
                         #action // Call transition action
                         #entry_action_calls // Call entry actions after action
                         self.current_state = next_state;
                        return true; // Transition occurred
                    }
                },
                (None, Some(action)) => quote! {
                     #exit_action_calls
                     let next_state = #state_enum_name::#to_state_ident;
                     #action
                     #entry_action_calls
                     self.current_state = next_state;
                    return true;
                },
                (Some(guard), None) => quote! {
                    if #guard {
                        #exit_action_calls
                        let next_state = #state_enum_name::#to_state_ident;
                        #entry_action_calls // Call entry actions even if no transition action
                        self.current_state = next_state;
                        return true;
                    }
                },
                (None, None) => quote! {
                    #exit_action_calls
                    let next_state = #state_enum_name::#to_state_ident;
                    #entry_action_calls
                    self.current_state = next_state;
                    return true;
                },
            };

            // Construct the full match arm for this (state, event) pair
            Ok(quote! {
                // Match against (&State, &Event)
                (#state_enum_name::#from_state_ident, #event_match_pattern) => {
                    #transition_logic
                    // If guard fails or no transition defined for this specific event variant under this state, fall through
                }
            })
        })
        .collect::<Result<Vec<_>, _>>()?; // Collect Results, propagating CodegenError

    // Generate the `on_event` method
    let on_event_method = quote! {
        /// Processes an event and attempts to transition the state machine.
        /// Returns `true` if a transition occurred, `false` otherwise.
        #[allow(unused_variables)] // event might be unused if no transitions use it directly
        pub fn on_event(&mut self, event: Event) -> bool { // Take event by value
            let current_state = self.current_state.clone(); // Clone current state for callbacks
            match (&self.current_state, &event) { // Match against references
                #(#on_event_match_arms)*
                // Default case: No transition for this state/event combination
                _ => false,
            }
        }
    };

    // Generate the `new` method
    let callbacks_param = quote! { callbacks: C };
    let new_method = quote! {
        /// Creates a new instance of the state machine in its initial state.
        pub fn new(#callbacks_param) -> Self { // Take Callbacks implementation
            Self {
                current_state: #initial_state_assignment,
                callbacks, // Store the provided callbacks implementation
            }
        }
    };

    // Generate the `current_state` getter method
    let current_state_method = quote! {
        /// Returns the current state.
        pub fn current_state(&self) -> &#state_enum_name {
            &self.current_state
        }
    };

    // Generate the impl block
    let impl_block = quote! {
        // The generic C requires the Callbacks trait bound
        impl<C: #callbacks_trait_name> #machine_struct_name<C> {
            #new_method
            #on_event_method
            #current_state_method
        }
    };

    Ok(impl_block)
}

/// Generates the Event enum definition with associated data structs.
fn generate_event_enum_and_structs(ast: &StateMachine, derive_tokens: &TokenStream) -> TokenStream {
    let event_enum_name = format_ident!("Event");
    // Use just "Payload" as the suffix convention
    let payload_suffix = format_ident!("Payload");

    let mut event_structs = Vec::new();
    let variants = ast
        .events
        .iter()
        .map(|event_item| {
            let variant_name = &event_item.name; // Use the Ident directly
            let variant_doc_comment = generate_rust_doc_comment(&event_item.annotations);

            if event_item.fields.is_empty() {
                // Event without payload
                quote! {
                    #variant_doc_comment
                    #variant_name
                }
            } else {
                // Event with payload struct
                // Corrected struct name generation
                let struct_name = format_ident!("{}{}", variant_name, payload_suffix);
                let struct_doc_comment = generate_rust_doc_comment(&event_item.annotations); // Use event doc for struct too?

                let fields = event_item.fields.iter().map(|field| {
                    let field_name = &field.name;
                    let field_type_ts = map_field_type_to_rust_type(&field.field_type);
                    let field_doc_comment = generate_rust_doc_comment(&field.annotations);
                    quote! {
                        #field_doc_comment
                        pub #field_name: #field_type_ts
                    }
                });

                // Generate the payload struct definition
                event_structs.push(quote! {
                    #struct_doc_comment
                    #derive_tokens // Derive traits for payload struct too
                    pub struct #struct_name {
                        #(#fields),*
                    }
                });

                // Generate the enum variant with the payload struct
                quote! {
                    #variant_doc_comment
                    #variant_name(#struct_name)
                }
            }
        })
        .collect::<Vec<_>>(); // Collect variants

    let event_enum_doc_comment = generate_rust_doc_comment(&[]); // TODO: Get annotations for the enum itself?

    quote! {
        // --- Event Payload Structs ---
        #(#event_structs)*

        // --- Event Enum ---
        #event_enum_doc_comment
        #derive_tokens // Use the same derives as State and Machine
        pub enum #event_enum_name {
            #(#variants),*
        }
    }
}

/// Generates Rust code from a StateMachine AST node (from parser).
///
/// # Arguments
///
/// * `ast` - A parsed `StateMachine` from `fsm_dsl::parser`.
///
/// # Returns
///
/// * `Result<String, CodegenError>` - Generated Rust code string, or an error.
pub fn generate_rust_code(ast: &StateMachine) -> Result<String, CodegenError> {
    let state_enum_name = format_ident!("State");
    let machine_struct_name = format_ident!("{}", ast.name); // Use name from AST
    let event_enum_name = format_ident!("Event"); // Consistent event enum name
    let callbacks_trait_name = format_ident!("{}Callbacks", ast.name); // e.g., LightSwitchCallbacks

    // State enum generation
    let state_variants = ast.states.iter().map(|s| {
        let variant_name = format_ident!("{}", s.name);
        let doc_comment = generate_rust_doc_comment(&s.annotations);
        quote! {
            #doc_comment // Doc comment first
            #variant_name
        }
    });
    let state_enum_doc_comment = generate_rust_doc_comment(&[]); // TODO: Get annotations for the enum itself?
    let state_enum_derive = quote! { #[derive(Debug, Clone, PartialEq, Eq, Hash)] }; // Define derive separately
    let state_enum = quote! {
        #state_enum_doc_comment // Doc comment first
        #state_enum_derive // Derive second
        // Add Eq, Hash back if no Float types are used in practice or handled
        pub enum #state_enum_name {
            #(#state_variants),*
        }
    };

    // Event enum and payload struct generation
    let event_derive_tokens = quote! { #[derive(Debug, Clone, PartialEq)] };
    let event_defs = generate_event_enum_and_structs(ast, &event_derive_tokens);

    // --- Callback Trait Generation ---
    let mut guards: HashSet<&proc_macro2::Ident> = HashSet::new();
    let mut actions: HashSet<&proc_macro2::Ident> = HashSet::new(); // Includes transition, entry, exit actions

    for transition in &ast.transitions {
        for element in &transition.elements {
            match element {
                TransitionElement::Guard { function, .. } => {
                    guards.insert(function);
                }
                TransitionElement::Action { function, .. } => {
                    actions.insert(function);
                }
                _ => {}
            }
        }
    }
    for state in &ast.states {
        for entry_action in &state.entry_actions {
            actions.insert(entry_action);
        }
        for exit_action in &state.exit_actions {
            actions.insert(exit_action);
        }
    }

    // Define the standard event parameter signature for the trait's default methods
    let event_param_sig = quote! { & #event_enum_name }; // Use reference to Event enum

    let guard_methods = guards.iter().map(|guard_name| {
         quote! {
              #[allow(unused_variables)]
              /// Guard condition for transition: #guard_name
              fn #guard_name(&self, current_state: &State, event: #event_param_sig) -> bool {
                  eprintln!("[WARN] Guard '{}' not implemented, returning default false.", stringify!(#guard_name));
                  false
              }
         }
     });

    let action_methods = actions.iter().map(|action_name| {
         quote! {
              #[allow(unused_variables)]
               /// Action executed during transition or on entry/exit: #action_name
              fn #action_name(&mut self, current_state: &State, event: #event_param_sig, next_state: &State) {
                  eprintln!("[WARN] Action '{}' not implemented.", stringify!(#action_name));
                  // Default action is no-op
              }
         }
     });

    // Generate the Callbacks trait
    let callbacks_trait = quote! {
        /// Trait for implementing state machine actions and guards.
        ///
        /// User code should implement this trait to provide the actual logic
        /// for state transitions. Default implementations are provided that
        /// print warnings and return default values (false for guards, no-op for actions).
        pub trait #callbacks_trait_name {
            #(#guard_methods)*
            #(#action_methods)*
            // Consider adding a context parameter if complex state is needed outside the FSM struct
            // fn get_context(&self) -> &MyContext;
            // fn get_context_mut(&mut self) -> &mut MyContext;
        }
    };

    // Machine struct definition
    let machine_struct_doc_comment = generate_rust_doc_comment(&ast.annotations);
    let machine_struct_derive = quote! { #[derive(Debug, Clone, PartialEq)] }; // Define derive separately
    let machine_struct = quote! {
         #machine_struct_doc_comment
         #machine_struct_derive
         pub struct #machine_struct_name<C: #callbacks_trait_name> { // Require trait bound C
             // Make current_state public for inspection/assertion
             pub current_state: #state_enum_name,
             // Store the Callbacks implementation
             callbacks: C,
         }
    };

    // Impl block generation (Pass only trait name)
    let impl_block = generate_impl_block(ast, &callbacks_trait_name)?;

    // Generate Default impl
    let default_impl = quote! {
        // Only implement Default if the Callbacks implementation is also Default
        impl<C: #callbacks_trait_name + Default> Default for #machine_struct_name<C> {
            fn default() -> Self {
                Self::new(C::default()) // Call new with default callbacks
            }
        }
    };

    // Combine all parts
    let combined_code = quote! {
         #state_enum
         #event_defs
         #callbacks_trait // Define trait before struct that uses it
         #machine_struct
         #impl_block
         #default_impl
    };

    // Format the generated code using prettyplease
    // Parse the TokenStream into a syn::File
    let syntax_tree: syn::File = match syn::parse2(combined_code.clone()) {
        // Clone for error reporting
        Ok(tree) => tree,
        Err(e) => {
            // Return an error that includes the generated code for debugging
            eprintln!("--- Failed to parse generated code ---");
            eprintln!("{}", combined_code.to_string());
            eprintln!("--- End generated code ---");
            return Err(CodegenError::SynParseError(e, combined_code.to_string()));
        }
    };

    // Format using prettyplease
    let formatted_code = prettyplease::unparse(&syntax_tree);

    Ok(formatted_code)
}

/// Generates a Cap'n Proto schema (.capnp) from the FSM AST.
///
/// # Arguments
///
/// * `file_ast` - The parsed `SsotFile` structure (needed for file ID).
/// * `machine_ast` - The specific `StateMachine` structure to generate the schema for.
///
/// # Returns
///
/// A `Result` containing the Cap'n Proto schema string or a `CodegenError`.
pub fn generate_capnp_schema(
    file_ast: &SsotFile, // Updated signature
    machine_ast: &StateMachine,
) -> Result<String, CodegenError> {
    // Use the internal function from the capnp module
    codegen_capnp::generate_capnp_schema_internal(file_ast, machine_ast)
}

/// Generates TypeScript type definitions (.types.ts) from the FSM AST.
///
/// # Arguments
///
/// * `ast` - The parsed `StateMachine` structure.
///
/// # Returns
///
/// A `Result` containing the TypeScript type definition string or a `CodegenError`.
pub fn generate_typescript_types(ast: &StateMachine) -> Result<String, CodegenError> {
    // Use the internal function from the ts module
    codegen_ts::generate_typescript_types_internal(ast)
}

/// Generates an XState machine definition string from the FSM AST.
///
/// # Arguments
/// * `ast` - A reference to the `StateMachine` AST node.
///
/// # Returns
/// A `Result` containing the generated XState machine definition (e.g., as a JS object literal string) or a `CodegenError`.
pub fn generate_xstate_machine(ast: &StateMachine) -> Result<String, CodegenError> {
    // Use the internal function from the xstate module
    codegen_xstate::generate_xstate_machine_internal(ast)
}

/// Generates an SCXML document string from the FSM AST.
///
/// # Arguments
/// * `ast` - A reference to the `StateMachine` AST node.
///
/// # Returns
/// A `Result` containing the generated SCXML document as a `String` or a `CodegenError`.
pub fn generate_scxml(ast: &StateMachine) -> Result<String, CodegenError> {
    // Use the internal function from the scxml module
    codegen_scxml::generate_scxml_internal(ast)
}

// Error type
#[derive(Debug, thiserror::Error)]
pub enum CodegenError {
    #[error("Failed to parse generated code: {0}\\n--- Generated Code ---\\n{1}")]
    SynParseError(syn::Error, String),
    #[error("AST validation error: {0}")]
    AstValidationError(String),
    #[error("Code generation failed: {0}")]
    GenerationError(String),
    #[error("I/O error during code formatting: {0}")]
    FormatIoError(#[from] std::io::Error),
    #[error("Failed to format generated code: {0}")]
    FormatError(String),
    // Potential future errors: IO errors, etc.
}

// Add the From implementation here, once, centrally.
impl From<std::fmt::Error> for CodegenError {
    fn from(err: std::fmt::Error) -> Self {
        CodegenError::GenerationError(format!("Failed to write to string: {}", err))
    }
}

// --- Unit Tests ---
#[cfg(test)]
mod tests {
    use super::*;
    use fsm_dsl::parser::parse_str; // Import the CORRECT parser function
                                    // Import necessary AST types for helper functions
    use fsm_dsl::ast::{
        Annotation, AnnotationValue, FieldDef, FieldType, MessageItem, StateItem, StateMachine,
        TransitionElement, TransitionItem,
    };

    use syn::parse_file as syn_parse_file; // Import for code parsing in tests

    // --- Define shared constants for tests ---
    const ANNOTATED_MACHINE_SSOT: &str = r#"
 @0xdeadbeefcafe0001;

 $description("This is the main machine.");
 stateMachine AnnotatedMachine {
     $initial(Idle);
     states {
         $description("Waiting state.");
         Idle @0;
         $description("Active state.");
         Running @1;
     }
     events {
         $description("Starts the machine.");
         event Start @0 {
             $description("The user ID.");
             userId @0 : UInt64;
         }
         $description("Stops the machine.");
         event Stop @1; // Use semicolon instead of {} for empty event
     }
     transitions {
         transition StartIdle from Idle to Running { on @0 Start; action @0 start_action; }
         transition StopRunning from Running to Idle { on @1 Stop; guard @0 can_stop; }
     }
 }
 "#;

    // Helper function to create identifiers for tests
    fn ident(s: &str) -> proc_macro2::Ident {
        proc_macro2::Ident::new(s, proc_macro2::Span::call_site())
    }

    // Helper to create a basic StateMachine AST for testing
    fn create_test_ast() -> StateMachine {
        StateMachine {
            name: ident("TestMachine"),
            annotations: vec![Annotation {
                name: ident("initial"),
                value: Some(AnnotationValue::Identifier(ident("Idle"))),
            }],
            events: vec![
                MessageItem {
                    name: ident("Event1"),
                    ordinal: 0, // Use u64 directly
                    annotations: vec![],
                    fields: vec![],
                },
                MessageItem {
                    name: ident("Event2"),
                    ordinal: 1, // Use u64 directly
                    annotations: vec![],
                    fields: vec![],
                },
                MessageItem {
                    name: ident("EventWithPayload"),
                    ordinal: 2, // Use u64 directly
                    annotations: vec![],
                    fields: vec![FieldDef {
                        name: ident("data"),
                        ordinal: 0, // Use u64 directly
                        annotations: vec![],
                        field_type: FieldType::UInt32,
                    }],
                },
            ],
            states: vec![
                StateItem {
                    name: ident("Idle"),
                    ordinal: 0, // Use u64 directly
                    annotations: vec![],
                    entry_actions: vec![], // Use vec![] for empty
                    exit_actions: vec![],  // Use vec![] for empty
                },
                StateItem {
                    name: ident("Active"),
                    ordinal: 1, // Use u64 directly
                    annotations: vec![],
                    entry_actions: vec![], // Use vec![] for empty
                    exit_actions: vec![],  // Use vec![] for empty
                },
            ],
            transitions: vec![
                TransitionItem {
                    name: Some(ident("T1")), // Wrap name in Some
                    from: ident("Idle"),
                    to: ident("Active"),
                    annotations: vec![],
                    elements: vec![TransitionElement::On {
                        ordinal: 0,
                        event: ident("Event1"),
                    }], // Use u64 directly
                },
                TransitionItem {
                    name: Some(ident("T2")), // Wrap name in Some
                    from: ident("Active"),
                    to: ident("Idle"),
                    annotations: vec![],
                    elements: vec![TransitionElement::On {
                        ordinal: 1,
                        event: ident("Event2"),
                    }], // Use u64 directly
                },
                TransitionItem {
                    name: Some(ident("T3WithAction")), // Wrap name in Some
                    from: ident("Idle"),
                    to: ident("Active"),
                    annotations: vec![],
                    elements: vec![
                        TransitionElement::On {
                            ordinal: 2,
                            event: ident("EventWithPayload"),
                        }, // Use u64 directly
                        TransitionElement::Action {
                            ordinal: 0,
                            function: ident("do_something"),
                        }, // Use u64 directly
                    ],
                },
            ],
            context: vec![], // Add missing context field
        }
    }

    // Helper to parse and format code for comparison
    fn parse_and_format(code: &str) -> String {
        let parsed_file = syn_parse_file(code).expect("Failed to parse generated code");
        prettyplease::unparse(&parsed_file)
    }

    // Example Callbacks struct for testing (trait itself is generated and tested via string contains)
    #[derive(Default, Debug, Clone, PartialEq)]
    struct TestCallbacks;

    #[test]
    fn generates_basic_structures() {
        let ast = create_test_ast();
        let result = generate_rust_code(&ast);
        assert!(result.is_ok(), "Rust generation failed: {:?}", result.err());
        let code = result.unwrap();
        let formatted_code = parse_and_format(&code);

        // Basic checks (adjust based on actual generation)
        assert!(formatted_code.contains("pub enum State"));
        assert!(formatted_code.contains("Idle"));
        assert!(formatted_code.contains("Active"));
        assert!(formatted_code.contains("pub enum Event"));
        assert!(formatted_code.contains("Event1"));
        assert!(formatted_code.contains("Event2"));
        assert!(formatted_code.contains("pub struct EventWithPayloadPayload")); // Check payload struct
        assert!(formatted_code.contains("EventWithPayload(EventWithPayloadPayload)")); // Check enum variant with payload
        assert!(formatted_code.contains("pub struct TestMachine<C: TestMachineCallbacks>")); // Check struct definition with generic
                                                                                             // Check the generated trait string
        assert!(formatted_code.contains("pub trait TestMachineCallbacks"));
        // Check the action method exists in the trait string
        assert!(formatted_code.contains(
            "fn do_something(&mut self, current_state: &State, event: &Event, next_state: &State)"
        ));
    }

    #[test]
    fn generates_impl_block_and_new() {
        let ast = create_test_ast();
        let result = generate_rust_code(&ast);
        assert!(result.is_ok(), "Rust generation failed: {:?}", result.err());
        let code = result.unwrap();
        let formatted_code = parse_and_format(&code);

        assert!(formatted_code.contains("impl<C: TestMachineCallbacks> TestMachine<C>")); // Check impl block with generic
        assert!(formatted_code.contains("pub fn new(callbacks: C) -> Self")); // Check new signature
        assert!(formatted_code.contains("current_state: State::Idle")); // Check initial state assignment
        assert!(formatted_code.contains("callbacks,")); // Check callbacks assignment
        assert!(formatted_code
            .contains("impl<C: TestMachineCallbacks + Default> Default for TestMachine<C>")); // Check Default impl
        assert!(formatted_code.contains("Self::new(C::default())"));
    }

    #[test]
    fn generates_on_event_method_with_transitions() {
        let ast = create_test_ast();
        let result = generate_rust_code(&ast);
        assert!(result.is_ok(), "Rust generation failed: {:?}", result.err());
        let code = result.unwrap();
        let formatted_code = parse_and_format(&code);

        // Check on_event signature and logic
        assert!(formatted_code.contains("pub fn on_event(&mut self, event: Event) -> bool"));
        assert!(formatted_code.contains("match (&self.current_state, &event)"));
        assert!(formatted_code.contains("(State::Idle, &Event::Event1) =>")); // Check matching reference
        assert!(formatted_code.contains("self.current_state = State::Active;"));
        assert!(formatted_code.contains("return true;"));
        assert!(formatted_code.contains("(State::Active, &Event::Event2) =>"));
        assert!(formatted_code.contains("self.current_state = State::Idle;"));
        assert!(formatted_code.contains("(State::Idle, &Event::EventWithPayload { .. }) =>")); // Check payload matching
        assert!(formatted_code
            .contains("self.callbacks.do_something(&current_state, &event, &next_state);")); // Check action call
        assert!(formatted_code.contains("_ => false")); // Default case
    }

    #[test]
    fn generates_guard_and_action_placeholders_module() {
        // Need an AST with guards/actions
        let ast_with_callbacks = StateMachine {
            // Simplified AST for this test
            name: ident("CallbackMachine"),
            annotations: vec![Annotation {
                name: ident("initial"),
                value: Some(AnnotationValue::Identifier(ident("S1"))),
            }],
            events: vec![MessageItem {
                name: ident("E1"),
                ordinal: 0,
                annotations: vec![],
                fields: vec![],
            }], // Use u64 directly
            states: vec![
                StateItem {
                    name: ident("S1"),
                    ordinal: 0,
                    annotations: vec![],
                    entry_actions: vec![],
                    exit_actions: vec![],
                }, // Use u64 directly
                StateItem {
                    name: ident("S2"),
                    ordinal: 1,
                    annotations: vec![],
                    entry_actions: vec![],
                    exit_actions: vec![],
                },
            ], // Use u64 directly
            transitions: vec![TransitionItem {
                name: Some(ident("T1")), // Wrap name in Some
                from: ident("S1"),
                to: ident("S2"),
                annotations: vec![],
                elements: vec![
                    TransitionElement::On {
                        ordinal: 0,
                        event: ident("E1"),
                    }, // Use u64 directly
                    TransitionElement::Guard {
                        ordinal: 0,
                        function: ident("can_transition"),
                    }, // Use u64 directly
                    TransitionElement::Action {
                        ordinal: 1,
                        function: ident("perform_action"),
                    }, // Use u64 directly
                ],
            }],
            context: vec![], // Add missing context field
        };
        let result = generate_rust_code(&ast_with_callbacks);
        assert!(result.is_ok(), "Rust generation failed: {:?}", result.err());
        let code = result.unwrap();
        let formatted_code = parse_and_format(&code);

        println!(
            "-- CallbackMachine Code --\n{}\n-- End CallbackMachine Code --",
            formatted_code
        );

        // Check trait definition string contains the expected methods
        assert!(formatted_code.contains("pub trait CallbackMachineCallbacks"));
        // Check guard with default impl string representation
        assert!(formatted_code
            .contains("fn can_transition(&self, current_state: &State, event: &Event) -> bool {"));
        assert!(
            formatted_code.contains("eprintln!(\"[WARN] Guard 'can_transition' not implemented")
        );
        assert!(formatted_code.contains("false"));
        // Check action with default impl string representation
        assert!(formatted_code.contains("fn perform_action(&mut self, current_state: &State, event: &Event, next_state: &State) {"));
        assert!(
            formatted_code.contains("eprintln!(\"[WARN] Action 'perform_action' not implemented")
        );
    }

    #[test]
    fn handles_no_transitions_or_callbacks() {
        let simple_ast = StateMachine {
            name: ident("SimpleMachine"),
            annotations: vec![Annotation {
                name: ident("initial"),
                value: Some(AnnotationValue::Identifier(ident("OnlyState"))),
            }],
            events: vec![MessageItem {
                name: ident("DummyEvent"),
                ordinal: 0,
                annotations: vec![],
                fields: vec![],
            }], // Use u64 directly
            states: vec![StateItem {
                name: ident("OnlyState"),
                ordinal: 0,
                annotations: vec![],
                entry_actions: vec![],
                exit_actions: vec![],
            }], // Use u64 directly
            transitions: vec![], // No transitions
            context: vec![],     // Add missing context field
        };
        let result = generate_rust_code(&simple_ast);
        assert!(result.is_ok(), "Rust generation failed: {:?}", result.err());
        let code = result.unwrap();
        let formatted_code = parse_and_format(&code);

        // Check that impl block is generated, but on_event might be simple
        assert!(formatted_code.contains("impl<C: SimpleMachineCallbacks> SimpleMachine<C>")); // Still generates generic impl
                                                                                              // Check on_event signature
        assert!(formatted_code.contains("pub fn on_event(&mut self, event: Event) -> bool"));
        assert!(formatted_code.contains("match (&self.current_state, &event)"));
        // Should likely only contain the default arm if no transitions
        assert!(formatted_code.contains("_ => false"));
        // Check that the callback trait IS generated (even if empty)
        assert!(formatted_code.contains("pub trait SimpleMachineCallbacks"));
        // Check that the trait body is empty (or only contains default methods if we add some base ones later)
        assert!(formatted_code.contains("pub trait SimpleMachineCallbacks {}"));
    }

    #[test]
    fn generates_current_state_getter() {
        let ast = create_test_ast();
        let result = generate_rust_code(&ast);
        assert!(result.is_ok(), "Rust generation failed: {:?}", result.err());
        let code = result.unwrap();
        let formatted_code = parse_and_format(&code);

        assert!(formatted_code.contains("pub fn current_state(&self) -> &State"));
        assert!(formatted_code.contains("&self.current_state"));
    }

    // --- Tests using ANNOTATED_MACHINE_SSOT ---

    #[test]
    fn generates_rust_code_with_doc_comments() {
        let ast = parse_str(ANNOTATED_MACHINE_SSOT).unwrap();
        let machine = &ast.state_machines[0];
        let code = generate_rust_code(machine).unwrap();
        let formatted_code = parse_and_format(&code);

        println!(
            "-- AnnotatedMachine Code --\n{}\n-- End AnnotatedMachine Code --",
            formatted_code
        );

        // Check doc comments on generated items
        assert!(formatted_code.contains("/// Waiting state."));
        assert!(formatted_code.contains("/// Active state."));
        assert!(formatted_code.contains("/// Starts the machine."));
        assert!(formatted_code.contains("/// The user ID."));
        assert!(formatted_code.contains("/// Stops the machine."));
        assert!(formatted_code.contains("/// This is the main machine.")); // On struct
        assert!(formatted_code.contains("pub trait AnnotatedMachineCallbacks")); // Trait exists
        assert!(formatted_code
            .contains("/// Action executed during transitions or on entry/exit: start_action")); // Action in trait
        assert!(formatted_code.contains("/// Guard condition for transitions: can_stop")); // Guard in trait
        assert!(formatted_code.contains("impl<C: AnnotatedMachineCallbacks> AnnotatedMachine<C>")); // Impl block
        assert!(formatted_code.contains("/// Creates a new instance"));
        assert!(formatted_code.contains("/// Processes an event"));
        assert!(formatted_code.contains("/// Returns the current state."));
        assert!(formatted_code.contains(
            "impl<C: AnnotatedMachineCallbacks + Default> Default for AnnotatedMachine<C>"
        )); // Default impl
    }

    #[test]
    fn generates_capnp_schema_with_comments() {
        let ast = parse_str(ANNOTATED_MACHINE_SSOT).unwrap();
        let machine = &ast.state_machines[0];
        let result = generate_capnp_schema(&ast, machine);
        assert!(
            result.is_ok(),
            "Capnp generation failed: {:?}",
            result.err()
        );
        let schema = result.unwrap();
        assert!(schema.contains("@0xdeadbeefcafe0001;"));
        assert!(schema.contains("# This is the main machine."));
        assert!(schema.contains("enum State @0"));
        assert!(schema.contains("# Waiting state.\n  idle @0;")); // Adjusted to lowercase
        assert!(schema.contains("# Active state.\n  running @1;")); // Adjusted to lowercase
        assert!(schema.contains("struct StartPayload @2")); // Adjusted name
        assert!(schema.contains("# The user ID.\n    userId @0 :UInt64;"));
        assert!(schema.contains("union Event @1"));
        assert!(schema.contains("# Starts the machine.\n  start @0 :StartPayload;")); // Adjusted name & case
        assert!(schema.contains("# Stops the machine.\n  stop @1 :Void;")); // Adjusted case
                                                                            // Check transition ordinals are included (though not explicitly commented here)
    }

    #[test]
    fn generates_typescript_types_with_jsdoc() {
        let ast = parse_str(ANNOTATED_MACHINE_SSOT).unwrap();
        let machine = &ast.state_machines[0];
        let types = generate_typescript_types(machine).unwrap();

        println!(
            "-- AnnotatedMachine TS Types --\n{}\n-- End AnnotatedMachine TS Types --",
            types
        );

        assert!(types.contains("/**\n * This is the main machine.\n */"));
        // assert!(types.contains("export interface Context {")); // Context generation not implemented yet
        assert!(types.contains("export type State ="));
        assert!(types.contains("/**\n   * Waiting state.\n   */\n  \"Idle\""));
        assert!(types.contains("| /**\n   * Active state.\n   */\n  \"Running\""));
        assert!(types.contains("/**\n * Starts the machine.\n */"));
        assert!(types.contains("export interface StartPayload {")); // Adjusted name
        assert!(types.contains("/**\n   * The user ID.\n   */\n  userId: bigint;"));
        assert!(types.contains("export type Event ="));
        assert!(types.contains(
            "/**\n   * Starts the machine.\n   */\n  { type: \"Start\"; payload: StartPayload }" // Adjusted name
        ));
        assert!(types.contains("/**\n   * Stops the machine.\n   */\n| { type: \"Stop\" };"));
    }

    #[test]
    fn generates_xstate_config_with_comments() {
        let ast = parse_str(ANNOTATED_MACHINE_SSOT).unwrap();
        let machine = &ast.state_machines[0];
        let config = generate_xstate_machine(machine).unwrap();

        println!(
            "-- AnnotatedMachine XState Config --\n{}\n-- End AnnotatedMachine XState Config --",
            config
        );

        assert!(config.contains(
            "/**
 * This is the main machine.
 */"
        ));
        assert!(config.contains("id: \"AnnotatedMachine\""));
        assert!(config.contains("initial: \"Idle\""));
        assert!(config.contains("states: {"));
        assert!(config.contains("Idle: {"));
        assert!(config.contains("description: \"Waiting state.\""));
        assert!(config.contains("on: {"));
        assert!(config.contains("Start: {")); // Event name used directly
        assert!(config.contains("target: \"Running\""));
        assert!(config.contains("actions: \"start_action\"")); // Action name
        assert!(config.contains("Running: {"));
        assert!(config.contains("description: \"Active state.\""));
        assert!(config.contains("Stop: {"));
        assert!(config.contains("target: \"Idle\""));
        assert!(config.contains("guard: \"can_stop\"")); // Guard name
    }

    #[test]
    fn generates_scxml_doc_with_comments() {
        let ast = parse_str(ANNOTATED_MACHINE_SSOT).unwrap();
        let machine = &ast.state_machines[0];
        let scxml = generate_scxml(machine).unwrap();

        println!(
            "-- AnnotatedMachine SCXML --\n{}\n-- End AnnotatedMachine SCXML --",
            scxml
        );

        assert!(scxml.contains("<scxml"));
        assert!(scxml.contains("name=\"AnnotatedMachine\""));
        assert!(scxml.contains("initial=\"Idle\""));
        assert!(scxml.contains("<datamodel>"));
        assert!(scxml.contains("<!-- This is the main machine. -->")); // Comment in datamodel
        assert!(scxml.contains("<state id=\"Idle\">"));
        assert!(scxml.contains("<!-- Waiting state. -->")); // Comment inside state
        assert!(scxml.contains("<transition event=\"Start\" target=\"Running\">")); // Event name case preserved
        assert!(scxml.contains("<log label=\"action\" expr=\"\'start_action\'\"/>")); // Action as log expr
        assert!(scxml.contains("<state id=\"Running\">"));
        assert!(scxml.contains("<!-- Active state. -->"));
        assert!(scxml.contains("<transition event=\"Stop\" cond=\"can_stop\" target=\"Idle\"/>"));
        // Event name case preserved, cond for guard
    }
}
